// The alternatives audit of Fux's two-voice solutions (species 1-5), written to
// docs/fux/choices-audit.md. Usage: node tools/lab/choices-report.ts
import { writeFileSync } from "node:fs";
import { loadFuxRepository } from "../../src/music/fux/load-node.ts";
import { auditSpecies, pool, type ExerciseAudit } from "../../src/counterpoint/choices/audit.ts";
import { AUDIT_SPECIES as CHOICE_SPECIES } from "../../src/counterpoint/choices/corpus.ts";
import type { TierName } from "../../src/counterpoint/choices/score.ts";
import { readFileSync } from "node:fs";
import { trioSteps } from "../../src/game/trio.ts";
import { auditTrios, poolTrios } from "../../src/counterpoint/choices/trio.ts";

const repo = loadFuxRepository();
const pct = (a: number, b: number) => `${Math.round((100 * a) / b)}%`;
const ORDERS: [string, TierName[]][] = [
  ["errors > warnings > counsel > habit", ["errors", "warnings", "counsel", "habit"]],
  ["errors > warnings > counsel", ["errors", "warnings", "counsel"]],
  ["errors > habit", ["errors", "habit"]],
  ["errors > counsel > habit", ["errors", "counsel", "habit"]],
];

const out: string[] = [
  "# Alternatives audit of Fux's two-voice solutions",
  "",
  "Generated by `node tools/lab/choices-report.ts` (code: `src/counterpoint/choices/`). At every choice of",
  "Fux's solutions (a note; in fourth species a ligature), every candidate pitch is put in place of his,",
  "the rest of the line is kept, and the whole line is judged again with the rules in force at the",
  "exercise's step. Candidates: the mode's naturals and the accidentals Fux writes on that final, in a",
  "register window around the cantus. Habits are measured on the other solutions of the species",
  "(leave-one-out). Ranking compares the tiers in order. \"First\" counts ties; \"first where free\"",
  "counts only choices where more than one pitch was legal, and Fux's note first alone: the fair measure.",
  "",
];

for (const species of CHOICE_SPECIES) {
  const base = auditSpecies(repo, species);
  const p = pool(base);
  out.push(`## ${species[0].toUpperCase()}${species.slice(1)} species`, "");
  out.push(`${base.length} solutions, ${p.choices} choices; ${p.meanLegal.toFixed(1)} legal pitches per choice; Fux's note the only legal one at ${pct(p.forced, p.choices)} of choices; Fux illegal at ${p.fuxIllegal}.`, "");
  out.push("| ranking | Fux first | Fux first alone | first where free | mean rank |", "|---|---|---|---|---|");
  for (const [name, order] of ORDERS) {
    const q = pool(auditSpecies(repo, species, { order }));
    out.push(`| ${name} | ${pct(q.fuxFirst, q.choices)} | ${pct(q.fuxFirstAlone, q.choices)} | ${pct(q.fuxFirstFree, q.free)} (${q.free}) | ${q.meanRank.toFixed(2)} |`);
  }
  out.push("", "Legal pitches at each choice (first ranking; \\* where Fux's note is not ranked first):", "");
  out.push("| Fig. | final | cantus | choices |", "|---|---|---|---|");
  for (const a of base as ExerciseAudit[]) {
    out.push(`| ${a.line.figure} | ${a.line.modalFinal} | ${a.line.cantusVoice === "lower" ? "below" : "above"} | ${a.units.map((u) => `${u.legal}${u.rank !== 1 ? "\\*" : ""}`).join(" ")} |`);
  }
  out.push("");
}
const trios = trioSteps(JSON.parse(readFileSync("data/fux/three-voice/fux-three-voice.json", "utf8")));
const t = auditTrios(trios);
const tp = poolTrios(t);
out.push("## Three voices, first species", "");
out.push(`${t.length} solutions, ${tp.choices} choices (each of Fux's two added voices, bar by bar), judged by the game's three-voice rules (\`evaluateTrio\`, D90); habits: the weighted three-voice model (docs/fux/trio-habits-study.md: melodic moves, pairs of moves, the sonority, the chord member the voice takes, motion with each other voice). ${tp.meanLegal.toFixed(1)} legal pitches per choice; only Fux's note legal at ${pct(tp.forced, tp.choices)}; Fux illegal at ${tp.fuxIllegal}.`, "");
out.push("| ranking | Fux first | first where free | mean rank |", "|---|---|---|---|");
for (const [name, order] of ORDERS) {
  const q = poolTrios(auditTrios(trios, { order }));
  out.push(`| ${name} | ${pct(q.fuxFirst, q.choices)} | ${pct(q.fuxFirstFree, q.free)} (${q.free}) | ${q.meanRank.toFixed(2)} |`);
}
out.push("");
writeFileSync("docs/fux/choices-audit.md", out.join("\n"));
console.log("wrote docs/fux/choices-audit.md");
