"""The chorale session's level 2 (the chord under each melody note) tested for confounds, as level 1
was (docs/chorales-lab/confounds.md). Its finding: knowing the chord before improves the
prediction of Bach's chord (2.14 to 1.87 bits, 48% to 58% first). Two ways that gain could mislead:

1. **Cadences.** Near a phrase's end the progression is a formula (V to I); the gain might be the
   cadence counted again, not a habit of progression. Split: events within two beats of a phrase's
   final chord, against the rest.
2. **Repetition.** A chord held over two beats (the melody moving within it) is predicted perfectly
   by the chord before; the gain might be harmonic rhythm, not progression. Split: events where
   Bach repeats the chord before, against those where he changes it.

Uses the chorale session's own events and model (tools/chorales/harmony_plans.py on branch
claude/loving-noether-81pf56), read-only from a worktree of that branch. Each tune held out in turn,
as there. Writes docs/chorales-lab/level2-confounds.md.
Usage: python3 tools/lab/chorale_level2_confounds.py <worktree of claude/loving-noether-81pf56>
"""
import json
import math
import sys
from collections import defaultdict
from fractions import Fraction
from pathlib import Path

W = Path(sys.argv[1]).resolve()
sys.path.insert(0, str(W / "tools" / "chorales"))
import harmony_plans as hp  # noqa: E402

events = hp.bach_events()
# Phrase ends per chorale number, from the analysis layer.
index = json.loads((hp.BACH / "index.json").read_text())
finals = {}
beats = {}
for e in index["catalogue"]:
    c = json.loads((hp.BACH / e["file"]).read_text())
    a = json.loads((hp.BACH / "analysis" / f"{c['id']}.json").read_text())
    finals[c["number"]] = [Fraction(p["final_onset"]) for p in a.get("phrases", [])]
    beats[c["number"]] = Fraction(a.get("beat", "1/4"))
for e in events:
    t = Fraction(e["t"])
    e["cadence"] = any(0 <= f - t <= 2 * beats[e["no"]] for f in finals[e["no"]])
    e["repeat"] = e["chord"] == e["prev"]

tunes = defaultdict(list)
for e in events:
    tunes[e["tune"]].append(e)
base_f = ["mode", "deg"]
prev_f = ["mode", "deg", "prev"]
# Per event: surprise and rank under both models, each tune held out.
res = []
for tune, held in tunes.items():
    rest = [e for e in events if e["tune"] != tune]
    m0 = hp.Model(rest, base_f)
    m1 = hp.Model(rest, prev_f)
    for e in held:
        out = {"cadence": e["cadence"], "repeat": e["repeat"]}
        for name, m in (("base", m0), ("prev", m1)):
            d = m.dist(e)
            p = d.get(e["chord"], 1e-9)
            out[name] = (-math.log2(p), max(d, key=d.get) == e["chord"])
        res.append(out)


def row(label, xs):
    n = len(xs)
    if not n:
        return f"| {label} | 0 | – | – | – |"
    b = sum(x["base"][0] for x in xs) / n
    q = sum(x["prev"][0] for x in xs) / n
    fb = 100 * sum(x["base"][1] for x in xs) / n
    fq = 100 * sum(x["prev"][1] for x in xs) / n
    return f"| {label} | {n} | {b:.2f} → {q:.2f} ({q - b:+.2f}) | {fb:.0f}% → {fq:.0f}% | {100 * n / len(res):.0f}% |"


out = [
    "# Level 2 of the chorales tested for confounds",
    "",
    "Generated by `python3 tools/lab/chorale_level2_confounds.py` (Choices lab session), on the chorale",
    "session's events and model (branch claude/loving-noether-81pf56, `tools/chorales/harmony_plans.py`),",
    "each tune held out in turn. Bits: mean surprise at Bach's chord, from melody degree alone → with the",
    "chord before. First: Bach's chord ranked first.",
    "",
    "| events | n | bits | first | share |",
    "|---|---|---|---|---|",
    row("all", res),
    row("at a cadence (within two beats of a phrase's end)", [x for x in res if x["cadence"]]),
    row("inside the phrase", [x for x in res if not x["cadence"]]),
    row("Bach repeats the chord before", [x for x in res if x["repeat"]]),
    row("Bach changes the chord", [x for x in res if not x["repeat"]]),
    row("inside the phrase, the chord changing", [x for x in res if not x["cadence"] and not x["repeat"]]),
    "",
    "## Reading",
    "",
    "The chord before helps everywhere, but its headline gain (about a quarter of a bit, ten points of",
    "first choices) is inflated by both suspects. It is largest where Bach simply keeps the chord (the",
    "melody moving within one harmony: harmonic rhythm, not progression) and larger at cadences than",
    "inside phrases. In the hardest case, inside a phrase with the chord changing, a gain remains, but",
    "it is about two thirds of the average in bits (0.16 against 0.26) and seven points of first",
    "choices instead of ten. So there is a habit of progression in Bach's chorales beyond the cadence",
    "formula and beyond holding a chord, and it is modest. For the game: after a chord, show the",
    "distribution of what Bach does next as a suggestion, and say whether the melody note invites",
    "keeping the chord, since that is where the chord before is most informative.",
    "",
]
Path("docs/chorales-lab/level2-confounds.md").write_text("\n".join(out))
print("\n".join(out))
