"""Two of the chorale session's counts tested for confounds (its PRINCIPLES.md, CONCEPT.md):

1. Falling fifths in the fundamental bass (40% of root changes): a norm of root motion, or the
   cadences' formula counted many times? Root changes are split by where they fall: in the last two
   beats before a phrase's final chord (the cadence), or inside the phrase.
2. "The leading tone rises in the soprano and is free in the alto": the voice's name, or its place?
   For the third of a major chord whose root then falls a fifth (V to I, wherever it stands), does
   that voice rise a semitone to the next root? Split by voice, and by whether it is the top
   sounding note at that moment.

Read-only on the chorale branch (claude/loving-noether-81pf56, data/chorales/bach/analysis/), through
git. Writes docs/chorales-lab/confounds.md. Usage: python3 tools/lab/chorale_confounds.py
"""
import json
import re
import subprocess
from collections import Counter, defaultdict
from fractions import Fraction

BRANCH = "origin/claude/loving-noether-81pf56"
PC = {"C": 0, "D": 2, "E": 4, "F": 5, "G": 7, "A": 9, "B": 11}
STEP = "CDEFGAB"


def show(path):
    return subprocess.run(["git", "show", f"{BRANCH}:{path}"], capture_output=True, text=True, check=True).stdout


def pc(name):
    p = PC[name[0]]
    for ch in name[1:]:
        if ch == "#":
            p += 1
        elif ch in "b-":
            p -= 1
    return p % 12


def midi(pitch):
    m = re.match(r"^([A-G][#b-]*)(-?\d+)$", pitch)
    return 12 * (int(m.group(2)) + 1) + pc(m.group(1))


files = subprocess.run(["git", "ls-tree", "--name-only", f"{BRANCH}", "data/chorales/bach/analysis/"], capture_output=True, text=True, check=True).stdout.split()
motion = {"cadence": Counter(), "inside": Counter()}
lt = defaultdict(lambda: [0, 0])  # key -> [rises, total]
for path in files:
    if not path.endswith(".json"):
        continue
    d = json.loads(show(path))
    vs = [v for v in d["verticalities"] if v.get("on_beat") and v.get("root")]
    finals = [Fraction(p["final_onset"]) for p in d.get("phrases", [])]
    for a, b in zip(vs, vs[1:]):
        ra, rb = pc(a["root"]), pc(b["root"])
        if ra == rb:
            continue
        iv = (rb - ra) % 12
        kind = {5: "down a fifth", 7: "up a fifth", 2: "up a step", 1: "up a step", 10: "down a step", 11: "down a step", 8: "down a third", 9: "down a third", 3: "up a third", 4: "up a third", 6: "tritone"}[iv]
        tb = Fraction(b["t"])
        beat = Fraction(d.get("beat", "1/4"))  # times are in whole notes; the beat is the file's own
        near = any(0 <= f - tb <= 2 * beat for f in finals)
        motion["cadence" if near else "inside"][kind] += 1
        # The leading tone: the third of a major chord whose root falls a fifth next.
        if a.get("chord") in ("major", "dominant seventh") and iv == 5:
            labels = a.get("labels", {})
            for voice, role in labels.items():
                if role != "third" or not a["pitches"].get(voice) or not b["pitches"].get(voice):
                    continue
                p0, p1 = a["pitches"][voice], b["pitches"][voice]
                rises = midi(p1) - midi(p0) == 1
                top = max((x for x in a["pitches"].values() if x), key=midi) == p0
                for key in (f"voice:{voice}", f"top:{top}", f"{voice}|top:{top}"):
                    lt[key][0] += rises
                    lt[key][1] += 1


def share(c):
    n = sum(c.values())
    order = ["down a fifth", "up a fifth", "up a step", "down a third", "down a step", "up a third", "tritone"]
    return ", ".join(f"{k} {round(100 * c[k] / n)}%" for k in order if c[k]) + f" (n = {n})"


pct = lambda k: f"{round(100 * lt[k][0] / lt[k][1])}% ({lt[k][0]} of {lt[k][1]})" if lt[k][1] else "–"
out = [
    "# Two chorale counts tested for confounds",
    "",
    "Generated by `python3 tools/lab/chorale_confounds.py` (Choices lab session), read-only from the",
    "chorale session's analysis layer (`data/chorales/bach/analysis/`, branch claude/loving-noether-81pf56;",
    "Kirnberger's roots as that layer reads them). Beat-to-beat root changes, on the beat.",
    "",
    "## 1. Falling fifths: a norm, or the cadence counted many times?",
    "",
    "Root changes landing within the last two beats before (or on) a phrase's final chord, against all",
    "the others:",
    "",
    f"- at the cadence: {share(motion['cadence'])}",
    f"- inside the phrase: {share(motion['inside'])}",
    "",
    "## 2. The leading tone: the voice's name, or its place?",
    "",
    "The third of a major chord (or dominant seventh) whose root then falls a fifth (V to I, in",
    "whatever key): does the voice holding it rise a semitone to the next root?",
    "",
    "| voice | rises | when it is the top note | when it is not |",
    "|---|---|---|---|",
]
for v in ["soprano", "alto", "tenor", "bass"]:
    out.append(f"| {v} | {pct('voice:' + v)} | {pct(v + '|top:True')} | {pct(v + '|top:False')} |")
out += [
    "",
    f"Any voice, as the top note: {pct('top:True')}; not the top note: {pct('top:False')}.",
    "",
    "## Reading",
    "",
    "1. **Falling fifths are a norm, not only a cadence formula.** They are concentrated at cadences,",
    "   but inside phrases they are still the commonest root motion and about twice as common as the",
    "   rising fifth. The aggregate (40%) overstates them a little; the asymmetry stands.",
    "2. **The leading tone: outer voices against inner, rather than soprano against alto.** It rises",
    "   to the tonic in the soprano (77%) and the bass (95%: the dominant's first inversion going to",
    "   the tonic), and is free in the inner voices (alto 46%, tenor 55%), where it often falls to",
    "   the fifth of the next chord to complete it. Height alone cannot be separated from the soprano",
    "   here (the soprano is the top note in nearly every case), but the bass, the lowest voice,",
    "   resolves most of all: exposure in an outer voice, not height, goes with the resolution. For",
    "   the game: 'the leading tone rises in the outer voices' is the better-supported statement.",
    "",
]
open("docs/chorales-lab/confounds.md", "w").write("\n".join(out))
print("\n".join(out))
