// How hard is each of Fux's two-voice exercises, and do they get harder in his order? Difficulty
// (src/counterpoint/choices/difficulty.ts) from the audit, with the rules in force at each
// exercise's step (what the player faces). Written to docs/fux/difficulty.md.
// Usage: node tools/lab/difficulty-report.ts
import { writeFileSync } from "node:fs";
import { loadFuxRepository } from "../../src/music/fux/load-node.ts";
import { auditSpecies } from "../../src/counterpoint/choices/audit.ts";
import { CHOICE_SPECIES } from "../../src/counterpoint/choices/corpus.ts";
import { difficultyOf, spearman } from "../../src/counterpoint/choices/difficulty.ts";
import { rulesForStep } from "../../src/counterpoint/curriculum/index.ts";

const repo = loadFuxRepository();
const pct = (x: number) => `${Math.round(100 * x)}%`;
const head: string[] = [
  "# Difficulty of Fux's two-voice exercises",
  "",
  "Generated by `node tools/lab/difficulty-report.ts`. At each choice of Fux's solution, the audit",
  "puts every candidate pitch in place of his (the rest of his line kept) and counts the legal ones",
  "under the rules in force at the exercise's step. **Freedom** is log2 of the number of legal",
  "pitches, averaged over the choices: 0 bits when only one pitch is legal, 1 bit for two, 2 for four;",
  "less freedom, a harder exercise. **Forced**: the share of choices where only one pitch is legal.",
  "The measure describes how tight the exercise is around a good solution (Fux's line kept around",
  "each choice); it does not count solutions. **Order**: Spearman's correlation of freedom with the",
  "exercise's place in Fux's order (−1: each exercise tighter than the one before).",
  "",
];
const out: string[] = [];
const summary: string[] = ["| species | exercises | freedom (bits) | forced | rules in force (first → last) | order: correlation |", "|---|---|---|---|---|---|"];
for (const species of CHOICE_SPECIES) {
  const audits = auditSpecies(repo, species, { rules: "step" });
  const d = audits.map((a) => difficultyOf(a.units));
  const rules = audits.map((a) => rulesForStep(a.line.stepId).length);
  const all = difficultyOf(audits.flatMap((a) => a.units));
  const rho = spearman(audits.map((_, i) => i), d.map((x) => x.freedom));
  summary.push(`| ${species} | ${audits.length} | ${all.freedom.toFixed(2)} | ${pct(all.forced)} | ${rules[0]} → ${rules[rules.length - 1]} | ${rho >= 0 ? "+" : ""}${rho.toFixed(2)} |`);
  out.push(`## ${species[0].toUpperCase()}${species.slice(1)} species`, "");
  out.push("| # | Fig. | final | cantus | rules | legal per choice | forced | freedom (bits) |", "|---|---|---|---|---|---|---|---|");
  audits.forEach((a, i) => out.push(`| ${i + 1} | ${a.line.figure} | ${a.line.modalFinal} | ${a.line.cantusVoice === "lower" ? "below" : "above"} | ${rules[i]} | ${d[i].meanLegal.toFixed(1)} | ${pct(d[i].forced)} | ${d[i].freedom.toFixed(2)} |`));
  out.push("");
  console.log("done", species);
}
const reading = [
  "**Reading.** Across the species the exercises tighten steadily: the rules leave about two bits of",
  "freedom per choice in first species (some four or five pitches) and under one bit in fourth (half",
  "the choices forced). Within a species Fux's order is not one of difficulty: he goes through the",
  "modes (D, E, F, G, A, C), cantus below then above, and the correlations, over six to twelve",
  "exercises, are weak and of both signs. The first-species rise owes something to the rules added",
  "step by step (7 to 12). For the game: order generated practice by this measure within a species;",
  "Fux's own order needs no reordering, since it was never meant as a ladder of difficulty.",
  "",
];
writeFileSync("docs/fux/difficulty.md", [...head, ...summary, "", ...reading, ...out].join("\n"));
console.log([...head, ...summary].join("\n"));
