// Which of Fux's habits predict his choices? A forward selection of features (src/counterpoint/
// choices/features.ts), each exercise judged by a model learnt without it. Written to
// docs/fux/habits-study.md. Usage: node tools/lab/habits-study.ts
import { writeFileSync } from "node:fs";
import { loadFuxRepository } from "../../src/music/fux/load-node.ts";
import { contextFor } from "../../src/counterpoint/choices/audit.ts";
import { choicesAt } from "../../src/counterpoint/choices/alternatives.ts";
import { CHOICE_SPECIES, choiceUnits, fuxLines, onsets, type FuxLine } from "../../src/counterpoint/choices/corpus.ts";
import { ALL_FEATURES, arrival, featureBits, learnFeatures, type Feature, type FeatureInput } from "../../src/counterpoint/choices/features.ts";
import { buildHabits } from "../../src/counterpoint/choices/habits.ts";
import { legacyHabitOf } from "../../src/counterpoint/choices/score.ts";
import type { SpeciesId } from "../../src/counterpoint/layout.ts";
import { parsePitch } from "../../src/music/pitch.ts";

const repo = loadFuxRepository();
const unitsOf = (l: FuxLine) => choiceUnits(l.layout, l.line).filter((u) => /^[A-G]/.test(l.line[u[0]]));

interface Choice {
  li: number;
  unit: number[];
  fux: string;
  legal: string[];
}

/** Every choice of Fux's solutions with its legal pitches (the rules in force at the exercise's step). */
function collect(species: SpeciesId) {
  const lines = fuxLines(repo, species);
  const choices: Choice[] = [];
  lines.forEach((l, li) => {
    const ctx = contextFor(repo, l, lines, { rules: "step" });
    for (const unit of unitsOf(l)) {
      const c = choicesAt(ctx, l.line, unit, ["errors"]);
      choices.push({ li, unit, fux: l.line[unit[0]], legal: c.candidates.filter((x) => x.legal).map((x) => x.pitch) });
    }
  });
  return { lines, choices };
}

const trial = (l: FuxLine, unit: number[], p: string) => l.line.map((q, k) => (unit.includes(k) ? p : q));

interface Score {
  bits: number;
  top: number;
  free: number;
}

/** Mean surprise at Fux's note among the legal ones (bits), and how often it is ranked first alone. */
function evaluate(data: ReturnType<typeof collect>, cost: (li: number, x: FeatureInput) => number): Score {
  let b = 0;
  let top = 0;
  let free = 0;
  for (const c of data.choices) {
    if (c.legal.length < 2) continue;
    free++;
    const l = data.lines[c.li];
    const costs = c.legal.map((p) => cost(c.li, { layout: l.layout, cantus: l.cantus, line: trial(l, c.unit, p), cantusVoice: l.cantusVoice, unit: c.unit }));
    const fi = c.legal.indexOf(c.fux);
    const min = Math.min(...costs);
    const z = costs.reduce((a, x) => a + 2 ** -(x - min), 0);
    b += costs[fi] - min + Math.log2(z);
    if (costs[fi] === min && costs.filter((x) => x === min).length === 1) top++;
  }
  return { bits: b / free, top, free };
}

function withFeatures(data: ReturnType<typeof collect>, features: Feature[]): Score {
  const tables = data.lines.map((_, li) => learnFeatures(data.lines.filter((__, j) => j !== li), features, unitsOf));
  return evaluate(data, (li, x) => featureBits(tables[li], features, x));
}

const out: string[] = [
  "# Fux's habits: what predicts his choices",
  "",
  "Generated by `node tools/lab/habits-study.ts`. At every choice of Fux's two-voice solutions",
  "(species 1-4) where the rules leave more than one pitch, a model of his habits ranks the legal",
  "pitches; it is learnt from his other solutions only (the exercise judged is left out). Two",
  "measures: the mean surprise at the note Fux wrote, in bits (lower is better; with no model at all",
  "it is log2 of the number of legal pitches), and how often his note is ranked first, alone.",
  "Features are added one at a time, the one that lowers the surprise most each time, while any",
  "does (by at least 0.01 bits over all species).",
  "",
];

const data = Object.fromEntries(CHOICE_SPECIES.map((s) => [s, collect(s)])) as Record<SpeciesId, ReturnType<typeof collect>>;
const pooled = (f: (d: ReturnType<typeof collect>) => Score) => {
  const per = CHOICE_SPECIES.map((s) => f(data[s]));
  const free = per.reduce((a, x) => a + x.free, 0);
  return { per, bits: per.reduce((a, x) => a + x.bits * x.free, 0) / free, top: per.reduce((a, x) => a + x.top, 0), free };
};
const row = (name: string, r: ReturnType<typeof pooled>) =>
  `| ${name} | ${r.bits.toFixed(3)} | ${Math.round((100 * r.top) / r.free)}% | ${r.per.map((x) => `${x.bits.toFixed(2)} / ${Math.round((100 * x.top) / x.free)}%`).join(" | ")} |`;

out.push("| model | bits | first | " + CHOICE_SPECIES.map((s) => `${({ first: "1st", second: "2nd", third: "3rd", fourth: "4th", fifth: "5th" } as Record<string, string>)[s]} species (bits / first)`).join(" | ") + " |", "|---|---|---|" + CHOICE_SPECIES.map(() => "---").join("|") + "|");
const uniform = pooled((d) => evaluate(d, () => 0));
out.push(row("no model (every legal pitch alike)", uniform));
const current = pooled((d) => {
  const hab = d.lines.map((_, li) => buildHabits(d.lines.filter((__, j) => j !== li), d.lines[0].species));
  return evaluate(d, (li, x) => {
    const h = legacyHabitOf(hab[li], x.cantusVoice, x.layout, x.cantus, x.line, x.unit);
    return h.melodic + h.vertical;
  });
});
out.push(row("the Lab's model so far (melodic by role, vertical, successive downbeats)", current));

let chosen: Feature[] = [];
let best = uniform;
const steps: string[] = [];
for (;;) {
  let pick: Feature | null = null;
  let pickScore = best;
  for (const f of ALL_FEATURES.filter((x) => !chosen.includes(x))) {
    const r = pooled((d) => withFeatures(d, [...chosen, f]));
    if (r.bits < pickScore.bits - 0.01) {
      pick = f;
      pickScore = r;
    }
  }
  if (!pick) break;
  chosen = [...chosen, pick];
  best = pickScore;
  out.push(row(`+ ${pick.label} (summed)`, best));
  steps.push(pick.id);
}

/*
 * Weighted: the features overlap (the motion into a downbeat partly repeats the interval it
 * arrives at), so summing their surprisals counts the same evidence twice. A choice model learns
 * one weight per feature: P(pitch) ∝ 2^(-Σ w_f · bits_f). The feature tables are learnt without
 * the exercise judged, and so are the weights (fitted on the other exercises, all species pooled).
 */
interface Row {
  species: SpeciesId;
  li: number;
  /** x[c][f]: bits of feature f for legal candidate c; fux: index of Fux's note. */
  x: number[][];
  fux: number;
}
const rows: Row[] = [];
for (const s of CHOICE_SPECIES) {
  const d = data[s];
  const tables = d.lines.map((_, li) => learnFeatures(d.lines.filter((__, j) => j !== li), ALL_FEATURES, unitsOf));
  for (const c of d.choices) {
    if (c.legal.length < 2) continue;
    const l = d.lines[c.li];
    const x = c.legal.map((p) => {
      const input: FeatureInput = { layout: l.layout, cantus: l.cantus, line: trial(l, c.unit, p), cantusVoice: l.cantusVoice, unit: c.unit };
      return ALL_FEATURES.map((f) => featureBits(tables[c.li], [f], input));
    });
    rows.push({ species: s, li: c.li, x, fux: c.legal.indexOf(c.fux) });
  }
}
const F = ALL_FEATURES.length;
const LN2 = Math.LN2;
/** Mean negative log-likelihood (bits) of Fux's choices under weights w. */
function nll(w: number[], rs: Row[]): number {
  let t = 0;
  for (const r of rs) {
    const e = r.x.map((xc) => -LN2 * xc.reduce((a, v, f) => a + w[f] * v, 0));
    const m = Math.max(...e);
    const z = e.reduce((a, v) => a + Math.exp(v - m), 0);
    t += (m + Math.log(z) - e[r.fux]) / LN2;
  }
  return t / rs.length;
}
/** Weights ≥ 0 by projected gradient descent, a little L2 shrinkage. */
function fit(rs: Row[], mask: boolean[] = Array(F).fill(true)): number[] {
  let w = mask.map((m) => (m ? 0.3 : 0));
  const lambda = 0.002;
  for (let it = 0; it < 400; it++) {
    const g = Array(F).fill(0);
    for (const r of rs) {
      const e = r.x.map((xc) => -LN2 * xc.reduce((a, v, f) => a + w[f] * v, 0));
      const m = Math.max(...e);
      const ex = e.map((v) => Math.exp(v - m));
      const z = ex.reduce((a, v) => a + v, 0);
      for (let f = 0; f < F; f++) {
        let exp = 0;
        for (let c = 0; c < r.x.length; c++) exp += (ex[c] / z) * r.x[c][f];
        g[f] += r.x[r.fux][f] - exp;
      }
    }
    w = w.map((wf, f) => (mask[f] ? Math.max(0, wf - (0.5 * g[f]) / rs.length - lambda * wf) : 0));
  }
  return w;
}
/** Leave-one-exercise-out: weights fitted without the exercise, judged on it (per species when asked). */
function crossValidated(mask: boolean[], perSpecies = false) {
  const per = new Map<SpeciesId, { bits: number; top: number; free: number }>();
  for (const s of CHOICE_SPECIES) per.set(s, { bits: 0, top: 0, free: 0 });
  const groups = new Map<string, Row[]>();
  for (const r of rows) {
    const k = `${r.species}:${r.li}`;
    if (!groups.has(k)) groups.set(k, []);
    groups.get(k)!.push(r);
  }
  for (const [k, test] of groups) {
    const w = fit(rows.filter((r) => `${r.species}:${r.li}` !== k && (!perSpecies || r.species === test[0].species)), mask);
    for (const r of test) {
      const acc = per.get(r.species)!;
      acc.bits += nll(w, [r]);
      acc.free++;
      const cost = r.x.map((xc) => xc.reduce((a, v, f) => a + w[f] * v, 0));
      const min = Math.min(...cost);
      if (cost[r.fux] === min && cost.filter((c) => c === min).length === 1) acc.top++;
    }
  }
  const list = CHOICE_SPECIES.map((s) => {
    const a = per.get(s)!;
    return { bits: a.bits / a.free, top: a.top, free: a.free };
  });
  const free = list.reduce((a, x) => a + x.free, 0);
  return { per: list, bits: list.reduce((a, x) => a + x.bits * x.free, 0) / free, top: list.reduce((a, x) => a + x.top, 0), free };
}
const all = crossValidated(Array(F).fill(true));
out.push(row("**all features, weighted** (weights also learnt without the exercise)", all));
// What each feature adds: the weighted model without it.
const drops = ALL_FEATURES.map((f, i) => ({ f, r: crossValidated(ALL_FEATURES.map((_, j) => j !== i)) }));
const wAll = fit(rows);
out.push("", "Weights learnt on all exercises (bits of a feature count this much; 0 = no use once the others are in), and what leaving each feature out costs (cross-validated):", "");
out.push("| feature | weight | without it: bits | change |", "|---|---|---|---|");
ALL_FEATURES.forEach((f, i) => out.push(`| ${f.label} | ${wAll[i].toFixed(2)} | ${drops[i].r.bits.toFixed(3)} | ${(drops[i].r.bits - all.bits >= 0 ? "+" : "") + (drops[i].r.bits - all.bits).toFixed(3)} |`));
// The reduced model: the features whose removal costs something.
const keep = ALL_FEATURES.map((_, i) => drops[i].r.bits - all.bits > 0.005);
const reduced = crossValidated(keep);
const reducedPer = crossValidated(keep, true);
out.push("", "| model | bits | first | " + CHOICE_SPECIES.map((s) => `${({ first: "1st", second: "2nd", third: "3rd", fourth: "4th", fifth: "5th" } as Record<string, string>)[s]} species (bits / first)`).join(" | ") + " |", "|---|---|---|" + CHOICE_SPECIES.map(() => "---").join("|") + "|");
out.push(row("the Lab's model so far", current));
out.push(row("all features, weighted", all));
out.push(row(`kept features only (${ALL_FEATURES.filter((_, i) => keep[i]).map((f) => f.id).join(", ")}), one set of weights`, reduced));
out.push(row("kept features, weights per species", reducedPer));
const wKeep = fit(rows, keep);
out.push("", "Weights of the kept features (all exercises): " + ALL_FEATURES.map((f, i) => (keep[i] ? `${f.id} ${wKeep[i].toFixed(2)}` : "")).filter(Boolean).join(", ") + ".", "");
/*
 * The habits in words: what Fux does, counted on all his solutions of species 1-4 (two voices).
 */
{
  const lines = CHOICE_SPECIES.flatMap((sp) => data[sp].lines);
  const pc = (a: number, b: number) => (b ? `${Math.round((100 * a) / b)}%` : "–");
  // How downbeats are reached.
  const arr = new Map<string, number>();
  for (const l of lines) for (const u of unitsOf(l)) for (const k of arrival.keys({ layout: l.layout, cantus: l.cantus, line: l.line, cantusVoice: l.cantusVoice, unit: u }).slice(0, 1)) arr.set(k, (arr.get(k) ?? 0) + 1);
  const by = (kind: string) => ["contrary", "oblique", "similar", "parallel"].map((m) => [m, arr.get(`${m}>${kind}`) ?? 0] as [string, number]);
  const sum = (xs: [string, number][]) => xs.reduce((a, [, n]) => a + n, 0);
  const P = by("P");
  const I = by("I");
  out.push("## The habits in words", "", "Counted on all of Fux's two-voice solutions in species 1-4 (motion from the note before into the downbeat).", "");
  out.push("**How a downbeat is reached.**", "");
  out.push("| arriving at | contrary | oblique | similar | parallel | n |", "|---|---|---|---|---|---|");
  out.push(`| a perfect consonance | ${P.map(([, n]) => pc(n, sum(P))).join(" | ")} | ${sum(P)} |`);
  out.push(`| an imperfect consonance | ${I.map(([, n]) => pc(n, sum(I))).join(" | ")} | ${sum(I)} |`);
  out.push("");
  // What follows a leap.
  const after = new Map<string, Map<string, number>>();
  for (const l of lines) {
    const on = onsets(l.layout, l.line).map(([, p]) => parsePitch(p).midi);
    for (let j = 0; j + 2 < on.length; j++) {
      const a = on[j + 1] - on[j];
      const b = on[j + 2] - on[j + 1];
      const cls = Math.abs(a) <= 2 ? "step" : Math.abs(a) <= 4 ? "third" : "fourth or more";
      const next = b === 0 ? "repeat" : Math.sign(b) !== Math.sign(a) ? (Math.abs(b) <= 2 ? "back by step" : "back by leap") : Math.abs(b) <= 2 ? "on by step" : "on by leap";
      const key = `${a > 0 ? "up" : a < 0 ? "down" : "repeat"} a ${cls}`;
      if (a === 0) continue;
      if (!after.has(key)) after.set(key, new Map());
      after.get(key)!.set(next, (after.get(key)!.get(next) ?? 0) + 1);
    }
  }
  const nexts = ["back by step", "back by leap", "on by step", "on by leap", "repeat"];
  out.push("**What follows a move.**", "");
  out.push(`| after moving | ${nexts.join(" | ")} | n |`, "|---|" + nexts.map(() => "---").join("|") + "|---|");
  for (const key of ["up a step", "down a step", "up a third", "down a third", "up a fourth or more", "down a fourth or more"]) {
    const m = after.get(key) ?? new Map();
    const n = [...m.values()].reduce((a, b) => a + b, 0);
    out.push(`| ${key} | ${nexts.map((x) => pc(m.get(x) ?? 0, n)).join(" | ")} | ${n} |`);
  }
  out.push("");
}
console.log("KEEP", JSON.stringify(ALL_FEATURES.map((f, i) => [f.id, keep[i], wKeep[i]])));
writeFileSync("docs/fux/habits-study.md", out.join("\n"));
console.log(out.join("\n"));
