// Is "a leap is followed by a turn back" a principle of Fux's, or a shadow of the range? Von Hippel
// & Huron (Music Perception 18/1, 2000) argue that post-skip reversal is largely regression to the
// mean: a leap tends to carry a line far from the middle of its range, and from there most moves go
// back, leap or no leap. The test: split every move by where it lands (beyond the line's median in
// the direction it moved, or not) and compare what follows leaps with what follows steps that land
// alike. Written to docs/fux/leap-study.md. Usage: node tools/lab/leap-study.ts
import { readFileSync, writeFileSync } from "node:fs";
import { loadFuxRepository } from "../../src/music/fux/load-node.ts";
import { AUDIT_SPECIES, fuxLines, onsets } from "../../src/counterpoint/choices/corpus.ts";
import { trioSteps } from "../../src/game/trio.ts";
import { parsePitch } from "../../src/music/pitch.ts";
import { harmonic, isConsonant } from "../../src/counterpoint/interval.ts";

const repo = loadFuxRepository();
const midi = (p: string) => parsePitch(p).midi;

interface Corpus {
  name: string;
  lines: number[][];
}
const bySpecies = AUDIT_SPECIES.map((s) => ({ species: s, lines: fuxLines(repo, s).map((l) => onsets(l.layout, l.line).map(([, p]) => midi(p))) }));
/** Species 2-5 with, per note, whether it is consonant with the cantus where it begins. */
const consonantFlags = AUDIT_SPECIES.slice(1).map((sp, i) => ({
  tag: i,
  lines: fuxLines(repo, sp).map((l) => onsets(l.layout, l.line).map(([k, p]) => ({ m: midi(p), cons: isConsonant(harmonic(l.cantus[l.layout[k].bar], p)) }))),
}));
const two: Corpus = { name: "Fux's counterpoints, two voices (species 1-5)", lines: bySpecies.flatMap((x) => x.lines) };
const trios = trioSteps(JSON.parse(readFileSync("data/fux/three-voice/fux-three-voice.json", "utf8")));
const three: Corpus = { name: "Fux's added voices, three voices", lines: trios.flatMap((s) => s.fux.filter((_, v) => v !== s.cantusIndex).map((l) => l.map(midi))) };
const cfs: Corpus = { name: "Fux's cantus firmi", lines: repo.listCantusFirmi({ includeDistinctOnly: true }).map((c) => c.midi_sequence) };

const median = (xs: number[]) => {
  const s = [...xs].sort((a, b) => a - b);
  return s.length % 2 ? s[(s.length - 1) / 2] : (s[s.length / 2 - 1] + s[s.length / 2]) / 2;
};
type Size = "step" | "third" | "fourth+";
const sizeOf = (d: number): Size => (Math.abs(d) <= 2 ? "step" : Math.abs(d) <= 4 ? "third" : "fourth+");

interface Cell {
  n: number;
  back: number;
}
/** Wilson 95% interval for a proportion. */
function wilson(k: number, n: number): [number, number] {
  if (!n) return [0, 1];
  const z = 1.96;
  const p = k / n;
  const d = 1 + (z * z) / n;
  const c = p + (z * z) / (2 * n);
  const w = z * Math.sqrt((p * (1 - p)) / n + (z * z) / (4 * n * n));
  return [(c - w) / d, (c + w) / d];
}
const pct = (x: number) => `${Math.round(100 * x)}%`;
const show = (c: Cell) => (c.n ? `${pct(c.back / c.n)} (${c.back}/${c.n}; ${wilson(c.back, c.n).map(pct).join("–")})` : "–");

/** Reversal after each move, by its size and where it lands relative to the line's median. */
function table(c: Corpus) {
  const cells = new Map<string, Cell>();
  const add = (k: string, back: boolean) => {
    const x = cells.get(k) ?? { n: 0, back: 0 };
    x.n++;
    if (back) x.back++;
    cells.set(k, x);
  };
  for (const l of c.lines) {
    const m = median(l);
    for (let i = 0; i + 2 < l.length; i++) {
      const a = l[i + 1] - l[i];
      const b = l[i + 2] - l[i + 1];
      if (a === 0 || b === 0) continue;
      const beyond = a > 0 ? l[i + 1] > m : l[i + 1] < m;
      const back = Math.sign(b) !== Math.sign(a);
      add(`${sizeOf(a)}|${beyond ? "beyond" : "short"}`, back);
      add(`${sizeOf(a)}|all`, back);
    }
  }
  return cells;
}

const out: string[] = [
  "# After a leap: principle, or regression to the mean?",
  "",
  "Generated by `node tools/lab/leap-study.ts`. Von Hippel and Huron (\"Why do skips precede reversals?",
  "The effect of tessitura on melodic structure\", *Music Perception* 18/1, 2000) argue that the turn",
  "after a leap is largely regression to the mean: a leap tends to land far from the middle of the",
  "line's range, and from there most moves go back. If so, a leap that does *not* land beyond the",
  "middle should turn back no more often than a step that lands alike. Every move of Fux's lines",
  "(repeated notes left out) is classed by size and by where it lands: **beyond** the line's median",
  "pitch in the direction it moved, or **short** of it (at the median or on the side it came from).",
  "The cells give the share of moves followed by a turn back, with counts and a 95% interval.",
  "",
];
for (const c of [two, three, cfs]) {
  const t = table(c);
  const g = (k: string) => t.get(k) ?? { n: 0, back: 0 };
  out.push(`## ${c.name}`, "", "| move | all | landing beyond the median | landing short of it |", "|---|---|---|---|");
  for (const s of ["step", "third", "fourth+"] as Size[]) out.push(`| ${s} | ${show(g(`${s}|all`))} | ${show(g(`${s}|beyond`))} | ${show(g(`${s}|short`))} |`);
  out.push("");
}
/*
 * The same question with distance instead of two bins, and species held apart: a logistic model of
 * P(turn back) on how far beyond the median the move lands (semitones, signed in the direction of
 * the move), whether it was a third or a leap of a fourth or more, and the species (steps in third
 * and fifth species run on in scales, which a pooled table would mix in). Intervals: bootstrap over
 * whole lines (1000 resamples).
 */
interface Obs {
  x: number[];
  y: number;
}
function observations(groups: { tag: number; lines: number[][] }[], nTags: number): Obs[][] {
  // One array per line (for the bootstrap).
  return groups.flatMap((g) =>
    g.lines.map((l) => {
      const m = median(l);
      const obs: Obs[] = [];
      for (let i = 0; i + 2 < l.length; i++) {
        const a = l[i + 1] - l[i];
        const b = l[i + 2] - l[i + 1];
        if (a === 0 || b === 0) continue;
        const dist = Math.sign(a) * (l[i + 1] - m);
        const sz = sizeOf(a);
        const tags = Array.from({ length: nTags - 1 }, (_, t) => (g.tag === t + 1 ? 1 : 0));
        obs.push({ x: [1, dist / 6, sz === "third" ? 1 : 0, sz === "fourth+" ? 1 : 0, ...tags], y: Math.sign(b) !== Math.sign(a) ? 1 : 0 });
      }
      return obs;
    }),
  );
}
function logistic(data: Obs[]): number[] {
  const k = data[0].x.length;
  let w = Array(k).fill(0);
  for (let it = 0; it < 600; it++) {
    const g = Array(k).fill(0);
    for (const o of data) {
      const z = o.x.reduce((s, v, j) => s + v * w[j], 0);
      const p = 1 / (1 + Math.exp(-z));
      for (let j = 0; j < k; j++) g[j] += (o.y - p) * o.x[j];
    }
    w = w.map((v, j) => v + (1.5 * g[j]) / data.length);
  }
  return w;
}
let seed = 7;
const rand = () => ((seed = (seed * 16807) % 2147483647) / 2147483647);
function fitWithIntervals(perLine: Obs[][]) {
  const w = logistic(perLine.flat());
  const boots: number[][] = [];
  for (let r = 0; r < 1000; r++) {
    const sample = Array.from({ length: perLine.length }, () => perLine[Math.floor(rand() * perLine.length)]).flat();
    boots.push(logistic(sample));
  }
  const ci = (j: number) => {
    const xs = boots.map((b) => b[j]).sort((a, b) => a - b);
    return [xs[25], xs[974]];
  };
  return { w, ci };
}
const odds = (x: number) => Math.exp(x).toFixed(2);
out.push("## The model: distance from the middle, leap size, species", "");
out.push("Odds ratios for a turn back (95% bootstrap interval). Distance: per six semitones landed beyond the line's median in the direction of the move. Third and leap: against a step landing at the same distance, in the same species.", "");
out.push("| corpus | distance (per 6 semitones) | a third | a fourth or more |", "|---|---|---|---|");
for (const [name, groups, nTags] of [
  ["two voices, species 1-5 (species held apart)", bySpecies.map((x, i) => ({ tag: i, lines: x.lines })), AUDIT_SPECIES.length],
  ["two voices, first species only", [{ tag: 0, lines: bySpecies[0].lines }], 1],
  ["species 2-5, only moves landing on a consonance (species held apart)", "consonant", 4],
  ["three voices, added voices", [{ tag: 0, lines: three.lines }], 1],
  ["cantus firmi", [{ tag: 0, lines: cfs.lines }], 1],
] as [string, { tag: number; lines: number[][] }[] | "consonant", number][]) {
  const data =
    groups === "consonant"
      ? consonantFlags.flatMap((g) =>
          g.lines.map((l) => {
            // Keep the move only where its landing note is a consonance: a dissonant landing must go on by step (the rules), which is not a habit.
            const ms = l.map((x) => x.m);
            const per = observations([{ tag: g.tag, lines: [ms] }], nTags)[0];
            const keep: Obs[] = [];
            let j = 0;
            for (let i = 0; i + 2 < ms.length; i++) {
              if (ms[i + 1] - ms[i] === 0 || ms[i + 2] - ms[i + 1] === 0) continue;
              if (l[i + 1].cons) keep.push(per[j]);
              j++;
            }
            return keep;
          }),
        )
      : observations(groups, nTags);
  const { w, ci } = fitWithIntervals(data.filter((x) => x.length));
  const cell = (j: number) => `${odds(w[j])} (${ci(j).map(odds).join("–")})`;
  out.push(`| ${name} | ${cell(1)} | ${cell(2)} | ${cell(3)} |`);
}
out.push("");
out.push(
  "**Reading.** Where a line lands relative to its middle matters everywhere, and strongly: each six",
  "semitones beyond the median multiply the odds of turning back by about five to ten. What leap",
  "size adds once that is held fixed depends on the texture:",
  "",
  "- In whole-note lines (first species; the added voices in three voices) it adds nothing",
  "  measurable: in three voices the odds ratio for a leap of a fourth or more is 0.8 (interval",
  "  0.3-2.4); in first species, with few leaps, the interval is too wide to say (0.5-28). There the",
  "  turn after a leap is what von Hippel and Huron say it is: regression to the mean.",
  "- In the running lines of species 2-5 a leap turns back far more often than a step landing at",
  "  the same distance (odds about 6-8), and this survives keeping only moves that land on a",
  "  consonance (so it is not the rule that a dissonant passing note goes on by step). But the",
  "  comparison is with steps, and steps in running lines go on in the same direction (scales): the",
  "  contrast may be the inertia of steps as much as a rule for leaps. These data cannot separate",
  "  the two.",
  "- Fux's cantus firmi show a leap effect too (odds 4-5, wide interval), but they are few and were",
  "  composed to a convention that may include the turn itself (D8, constraint 11).",
  "",
  "So the habit reported in the habits study (\"after a leap of a fourth or more he turns back 76% up,",
  "95% down\") is, in whole-note writing, a shadow of the range rather than a principle; in running",
  "lines it is real but not yet explained.",
  "",
);
writeFileSync("docs/fux/leap-study.md", out.join("\n"));
console.log(out.join("\n"));
