// Does Fux imitate, or work with motives, in his species counterpoint? His solutions against
// counterpoints written by the lab's generator for the same cantus firmi (good local counterpoint,
// no notion of imitation or motive): if Fux shows more, it is a habit of his; if not, chance
// explains it. Written to docs/fux/motives-study.md. Usage: node tools/lab/motives-study.ts
import { readFileSync, writeFileSync } from "node:fs";
import { loadFuxRepository } from "../../src/music/fux/load-node.ts";
import { lastStepOf } from "../../src/counterpoint/choices/audit.ts";
import { CHOICE_SPECIES, fuxLines } from "../../src/counterpoint/choices/corpus.ts";
import { generateCounterpoint } from "../../src/counterpoint/choices/counterpoint.ts";
import { buildHabits } from "../../src/counterpoint/choices/habits.ts";
import { imitation, selfRepetition, skeleton, struck } from "../../src/counterpoint/choices/motives.ts";
import { buildTrioHabits, generateThirdVoice, trioAccidentals } from "../../src/counterpoint/choices/trio.ts";
import { fuxAccidentals, pitchesBetween, registerWindow } from "../../src/counterpoint/choices/vocabulary.ts";
import { rulesForStep } from "../../src/counterpoint/curriculum/index.ts";
import { trioSteps } from "../../src/game/trio.ts";

const repo = loadFuxRepository();
const acc = fuxAccidentals(repo);
const N = 12; // generated counterpoints per exercise
const ord = { first: "1st", second: "2nd", third: "3rd", fourth: "4th", fifth: "5th" } as Record<string, string>;

/** Where Fux's value falls among the generated ones: the share below it, ties counted half. */
const percentile = (x: number, null_: number[]) => (null_.filter((y) => y < x).length + 0.5 * null_.filter((y) => y === x).length) / null_.length;
const mean = (xs: number[]) => xs.reduce((a, b) => a + b, 0) / xs.length;
const f2 = (x: number) => x.toFixed(2);

interface Measures {
  imit: number;
  figures: number;
  longest: number;
}

const out: string[] = [
  "# Motives and imitation in Fux's species counterpoint",
  "",
  "Generated by `node tools/lab/motives-study.ts` (measures: `src/counterpoint/choices/motives.ts`).",
  "Each of Fux's solutions is set beside " + N + " counterpoints that the lab's generator writes for the",
  "same cantus firmus, in the same species and position: good local counterpoint by his rules and",
  "habits, with no notion of motive or imitation. What chance and the rules produce shows in them;",
  "what Fux adds shows as a difference.",
  "",
  "- **Imitation of the cantus**: the longest stretch of melodic intervals (diatonic steps, at any",
  "  transposition) the counterpoint shares with the cantus, displaced by one to four bars either way,",
  "  straight or inverted. In species 2-4 the counterpoint's downbeat notes are compared.",
  "- **Figures**: three-interval figures the counterpoint states twice or more (not overlapping),",
  "  transposed or not; **longest**: the longest figure it states twice.",
  "- **Percentile**: where Fux's value falls among the generated ones (50% = like them; near 100% =",
  "  more than they show), averaged over his exercises.",
  "",
];

out.push("## Two voices", "");
out.push("| species | exercises | imitation run: Fux / generated (percentile) | figures: Fux / generated (percentile) | longest figure: Fux / generated (percentile) |", "|---|---|---|---|---|");
const examples: string[] = [];
for (const species of CHOICE_SPECIES) {
  const lines = fuxLines(repo, species);
  const habits = buildHabits(lines, species);
  const rules = rulesForStep(lastStepOf(species));
  const fux: Measures[] = [];
  const gen: Measures[] = [];
  const pct: [number, number, number][] = [];
  for (const l of lines) {
    const measure = (line: (string | null)[]): Measures => {
      const sk = skeleton(l.layout, line);
      const r = selfRepetition(struck(l.layout, line));
      return { imit: imitation(sk, l.cantus).run, figures: r.figures, longest: r.longest };
    };
    const m = measure(l.line);
    const [lo, hi] = registerWindow(l.cantus, l.cantusVoice, l.line);
    const nulls: Measures[] = [];
    for (let seed = 1; nulls.length < N && seed < 3 * N; seed++) {
      try {
        const g = generateCounterpoint({ species, modalFinal: l.modalFinal, cantusVoice: l.cantusVoice, cantus: l.cantus, rules, vocabulary: pitchesBetween(lo, hi, acc[l.modalFinal]), habits: buildHabits(lines, species, [l.exerciseId]), seed: seed * 7919 });
        nulls.push(measure(g.line));
      } catch {
        /* no line for this seed */
      }
    }
    fux.push(m);
    gen.push(...nulls);
    pct.push([percentile(m.imit, nulls.map((x) => x.imit)), percentile(m.figures, nulls.map((x) => x.figures)), percentile(m.longest, nulls.map((x) => x.longest))]);
    const im = imitation(skeleton(l.layout, l.line), l.cantus);
    if (im.run >= 3) examples.push(`Fig. ${l.figure} (${ord[species]} species, ${l.modalFinal}): the counterpoint repeats ${im.run} of the cantus's intervals${im.inverted ? ", inverted," : ""} ${Math.abs(im.lag)} bar${Math.abs(im.lag) > 1 ? "s" : ""} ${im.lag > 0 ? "after" : "before"} it.`);
    void habits;
  }
  const col = (k: keyof Measures, i: number) => `${f2(mean(fux.map((x) => x[k])))} / ${f2(mean(gen.map((x) => x[k])))} (${Math.round(100 * mean(pct.map((p) => p[i])))}%)`;
  out.push(`| ${ord[species]} | ${lines.length} | ${col("imit", 0)} | ${col("figures", 1)} | ${col("longest", 2)} |`);
  console.log("done", species);
}
out.push("");
out.push(examples.length ? "Imitations of three intervals or more in Fux's solutions:" : "Fux's solutions contain no imitation of the cantus of three intervals or more.", "");
for (const e of examples) out.push(`- ${e}`);
out.push("");

// Three voices: each of Fux's added voices against a voice generated in its place (the other two kept).
out.push("## Three voices, first species", "");
const trios = trioSteps(JSON.parse(readFileSync("data/fux/three-voice/fux-three-voice.json", "utf8")));
const tacc = trioAccidentals(trios);
const tRows = { withCantus: [[], [], []] as number[][], withOther: [[], [], []] as number[][], figures: [[], [], []] as number[][] };
const trioExamples: string[] = [];
for (const s of trios) {
  const habits = buildTrioHabits(trios, [s.exerciseId]);
  const added = [0, 1, 2].filter((v) => v !== s.cantusIndex);
  for (const v of added) {
    const other = added.find((x) => x !== v)!;
    const given = [0, 1, 2].filter((x) => x !== v).map((x) => s.fux[x]) as [string[], string[]];
    const cantusOfGiven = ([0, 1, 2].filter((x) => x !== v).indexOf(s.cantusIndex) as 0 | 1);
    const placement = v === 0 ? "above" : v === 1 ? "between" : "below";
    const measure = (voice: string[], otherVoice: string[]) => [imitation(voice, s.cantus).run, imitation(voice, otherVoice).run, selfRepetition(voice).figures];
    const m = measure(s.fux[v], s.fux[other]);
    const nulls: number[][] = [];
    for (let seed = 1; nulls.length < N && seed < 3 * N; seed++) {
      try {
        const g = generateThirdVoice({ modalFinal: s.modalFinal, given, cantusOfGiven, placement, habits, accidentals: tacc[s.modalFinal] ?? [], seed: seed * 104729 });
        if (g.errors.length) continue;
        nulls.push(measure(g.voices[g.added], s.fux[other]));
      } catch {
        /* none */
      }
    }
    if (!nulls.length) continue;
    m.forEach((x, i) => {
      const key = (["withCantus", "withOther", "figures"] as const)[i];
      tRows[key][0].push(x);
      tRows[key][1].push(...nulls.map((n) => n[i]));
      tRows[key][2].push(percentile(x, nulls.map((n) => n[i])));
    });
    const io = imitation(s.fux[v], s.fux[other]);
    if (io.run >= 3) trioExamples.push(`Fig. ${s.figure} (${s.modalFinal}): one added voice repeats ${io.run} of the other's intervals${io.inverted ? ", inverted," : ""} ${Math.abs(io.lag)} bar${Math.abs(io.lag) > 1 ? "s" : ""} apart.`);
  }
}
out.push("| measure | Fux / generated (percentile) |", "|---|---|");
const t = (k: keyof typeof tRows, label: string) => out.push(`| ${label} | ${f2(mean(tRows[k][0]))} / ${f2(mean(tRows[k][1]))} (${Math.round(100 * mean(tRows[k][2]))}%) |`);
t("withCantus", "imitation run of an added voice with the cantus");
t("withOther", "imitation run between the two added voices");
t("figures", "three-interval figures stated twice in an added voice");
out.push("");
out.push(trioExamples.length ? "Imitations of three intervals or more between Fux's added voices:" : "No imitation of three intervals or more between Fux's added voices.", "");
for (const e of [...new Set(trioExamples)]) out.push(`- ${e}`);
out.push("");
out.push(
  "**Reading.** A percentile near 50% means Fux's lines show that much imitation or motivic repetition by",
  "the same chance that produces it in lines written without any notion of it: the rules and his local",
  "habits (steps, thirds, leaps turning back) yield short shared runs, mostly scalar. Twelve measures are",
  "compared here, so one of them straying to about 70% over a dozen exercises is what chance alone would",
  "often give. In the *Gradus* imitation is taught after Exercitium III, with fugue and double",
  "counterpoint (docs/fux/structure.md): the species exercises come before it.",
  "",
);
writeFileSync("docs/fux/motives-study.md", out.join("\n"));
console.log(out.join("\n"));
