// Which of Fux's habits predict his choices in three voices (first species)? The method of
// habits-study.ts on his sixteen three-voice solutions: features (src/counterpoint/choices/
// trio-features.ts) chosen one at a time, then weighted, each exercise judged by a model learnt
// without it. Written to docs/fux/trio-habits-study.md. Usage: node tools/lab/trio-habits-study.ts
import { readFileSync, writeFileSync } from "node:fs";
import { TRIO_FIRST_SPECIES } from "../../src/counterpoint/three-voice.ts";
import { trioSteps, type TrioStep } from "../../src/game/trio.ts";
import { buildTrioHabits, judgeTrio, trioAccidentals, legacyTrioHabit, trioVocabulary, type Position } from "../../src/counterpoint/choices/trio.ts";
import { ALL_TRIO_FEATURES, learnTrioFeatures, sonorityKey, trioFeatureBits, type TrioFeature, type TrioInput } from "../../src/counterpoint/choices/trio-features.ts";
import { parsePitch } from "../../src/music/pitch.ts";

const steps = trioSteps(JSON.parse(readFileSync("data/fux/three-voice/fux-three-voice.json", "utf8")));
const acc = trioAccidentals(steps);

interface Choice {
  si: number;
  v: number;
  k: number;
  fux: string;
  legal: string[];
}

const trial = (s: TrioStep, v: number, k: number, p: string) => s.fux.map((l, x) => (x === v ? l.map((q, j) => (j === k ? p : q)) : l));

// Every note of Fux's added voices, with the pitches the game's three-voice rules leave there.
const choices: Choice[] = [];
steps.forEach((s, si) => {
  for (let v = 0; v < 3; v++) {
    if (v === s.cantusIndex) continue;
    const vocab = trioVocabulary(s.fux[v], acc[s.modalFinal] ?? []);
    const pool = [...new Set([...vocab, ...s.fux[v]])];
    s.fux[v].forEach((fux, k) => {
      const legal = pool.filter((p) => judgeTrio({ modalFinal: s.modalFinal, cantusIndex: s.cantusIndex, rules: TRIO_FIRST_SPECIES }, trial(s, v, k, p)).errors.length === 0);
      choices.push({ si, v, k, fux, legal });
    });
  }
});
const free = choices.filter((c) => c.legal.length > 1);
const inputOf = (c: Choice, p: string): TrioInput => ({ voices: trial(steps[c.si], c.v, c.k, p), v: c.v, k: c.k, bars: steps[c.si].cantus.length });

interface Score {
  bits: number;
  top: number;
  free: number;
}

function evaluate(cost: (si: number, c: Choice, p: string) => number): Score {
  let b = 0;
  let top = 0;
  for (const c of free) {
    const costs = c.legal.map((p) => cost(c.si, c, p));
    const fi = c.legal.indexOf(c.fux);
    const min = Math.min(...costs);
    const z = costs.reduce((a, x) => a + 2 ** -(x - min), 0);
    b += costs[fi] - min + Math.log2(z);
    if (costs[fi] === min && costs.filter((x) => x === min).length === 1) top++;
  }
  return { bits: b / free.length, top, free: free.length };
}

const others = (si: number) => steps.filter((_, j) => j !== si);
const tablesFor = (features: TrioFeature[]) => steps.map((_, si) => learnTrioFeatures(others(si), features));
const withFeatures = (features: TrioFeature[]) => {
  const t = tablesFor(features);
  return evaluate((si, c, p) => trioFeatureBits(t[si], features, inputOf(c, p)));
};

const pct = (a: number, b: number) => `${Math.round((100 * a) / b)}%`;
const row = (name: string, r: Score) => `| ${name} | ${r.bits.toFixed(3)} | ${pct(r.top, r.free)} |`;

const out: string[] = [
  "# Fux's habits in three voices: what predicts his choices",
  "",
  "Generated by `node tools/lab/trio-habits-study.ts`, by the method of the two-voice study, on",
  `Fux's ${steps.length} three-voice solutions in first species (Exercitium II, Lectio I). At every note of his two`,
  "added voices where the game's three-voice rules (D90) leave more than one pitch " + `(${free.length} of ${choices.length}),`,
  "a model learnt from his other fifteen solutions ranks the legal pitches. Measures: the mean",
  "surprise at Fux's note (bits; lower is better) and how often it is ranked first, alone.",
  "",
  "| model | bits | first |",
  "|---|---|---|",
];
const uniform = evaluate(() => 0);
out.push(row("no model (every legal pitch alike)", uniform));
const hab = steps.map((_, si) => buildTrioHabits(steps, [steps[si].exerciseId]));
const current = evaluate((si, c, p) => legacyTrioHabit(hab[si], inputOf(c, p).voices, c.v as Position, c.k));
out.push(row("the Lab's model so far (melodic by staff, sonority, spacing, final top note; summed)", current));

let chosen: TrioFeature[] = [];
let best = uniform;
for (;;) {
  let pick: TrioFeature | null = null;
  let pickScore = best;
  for (const f of ALL_TRIO_FEATURES.filter((x) => !chosen.includes(x))) {
    const r = withFeatures([...chosen, f]);
    if (r.bits < pickScore.bits - 0.01) {
      pick = f;
      pickScore = r;
    }
  }
  if (!pick) break;
  chosen = [...chosen, pick];
  best = pickScore;
  out.push(row(`+ ${pick.label} (summed)`, best));
}

// Weighted (conditional logit), weights fitted without the exercise judged.
interface Row {
  si: number;
  x: number[][];
  fux: number;
}
const F = ALL_TRIO_FEATURES.length;
const allTables = tablesFor(ALL_TRIO_FEATURES);
const rows: Row[] = free.map((c) => ({
  si: c.si,
  fux: c.legal.indexOf(c.fux),
  x: c.legal.map((p) => ALL_TRIO_FEATURES.map((f) => trioFeatureBits(allTables[c.si], [f], inputOf(c, p)))),
}));
const LN2 = Math.LN2;
function nll(w: number[], r: Row): number {
  const e = r.x.map((xc) => -LN2 * xc.reduce((a, v, f) => a + w[f] * v, 0));
  const m = Math.max(...e);
  const z = e.reduce((a, v) => a + Math.exp(v - m), 0);
  return (m + Math.log(z) - e[r.fux]) / LN2;
}
function fit(rs: Row[], mask: boolean[]): number[] {
  let w = mask.map((m) => (m ? 0.3 : 0));
  for (let it = 0; it < 400; it++) {
    const g = Array(F).fill(0);
    for (const r of rs) {
      const e = r.x.map((xc) => -LN2 * xc.reduce((a, v, f) => a + w[f] * v, 0));
      const m = Math.max(...e);
      const ex = e.map((v) => Math.exp(v - m));
      const z = ex.reduce((a, v) => a + v, 0);
      for (let f = 0; f < F; f++) {
        let exp = 0;
        for (let c = 0; c < r.x.length; c++) exp += (ex[c] / z) * r.x[c][f];
        g[f] += r.x[r.fux][f] - exp;
      }
    }
    w = w.map((wf, f) => (mask[f] ? Math.max(0, wf - (0.5 * g[f]) / rs.length - 0.002 * wf) : 0));
  }
  return w;
}
function crossValidated(mask: boolean[]): Score {
  let b = 0;
  let top = 0;
  for (let si = 0; si < steps.length; si++) {
    const test = rows.filter((r) => r.si === si);
    if (!test.length) continue;
    const w = fit(rows.filter((r) => r.si !== si), mask);
    for (const r of test) {
      b += nll(w, r);
      const cost = r.x.map((xc) => xc.reduce((a, v, f) => a + w[f] * v, 0));
      const min = Math.min(...cost);
      if (cost[r.fux] === min && cost.filter((c) => c === min).length === 1) top++;
    }
  }
  return { bits: b / rows.length, top, free: rows.length };
}
const everything = Array(F).fill(true);
const all = crossValidated(everything);
out.push(row("**all features, weighted** (weights also learnt without the exercise)", all));
const drops = ALL_TRIO_FEATURES.map((_, i) => crossValidated(ALL_TRIO_FEATURES.map((__, j) => j !== i)));
const wAll = fit(rows, everything);
out.push("", "Weights learnt on all sixteen exercises, and what leaving each feature out costs (cross-validated):", "");
out.push("| feature | weight | without it: bits | change |", "|---|---|---|---|");
ALL_TRIO_FEATURES.forEach((f, i) => out.push(`| ${f.label} | ${wAll[i].toFixed(2)} | ${drops[i].bits.toFixed(3)} | ${(drops[i].bits - all.bits >= 0 ? "+" : "") + (drops[i].bits - all.bits).toFixed(3)} |`));
const keep = ALL_TRIO_FEATURES.map((_, i) => drops[i].bits - all.bits > 0.005);
const reduced = crossValidated(keep);
const wKeep = fit(rows, keep);
out.push("", "| model | bits | first |", "|---|---|---|");
out.push(row("the Lab's model so far", current));
out.push(row("all features, weighted", all));
out.push(row(`kept features only (${ALL_TRIO_FEATURES.filter((_, i) => keep[i]).map((f) => f.id).join(", ")}), weighted`, reduced));
out.push("", "Weights of the kept features (all exercises): " + ALL_TRIO_FEATURES.map((f, i) => (keep[i] ? `${f.id} ${wKeep[i].toFixed(2)}` : "")).filter(Boolean).join(", ") + ".", "");

// The habits in words.
{
  const midi = (p: string) => parsePitch(p).midi;
  const son = new Map<string, number>();
  let bars = 0;
  for (const s of steps)
    for (let k = 0; k < s.cantus.length; k++) {
      const key = sonorityKey(s.fux.map((l) => l[k]));
      son.set(key, (son.get(key) ?? 0) + 1);
      bars++;
    }
  const top = [...son.entries()].sort((a, b) => b[1] - a[1]).slice(0, 8);
  out.push("## The habits in words", "", `**Sonorities** (figures above the bass), over all ${bars} bars of the sixteen solutions:`, "");
  out.push("| sonority | bars | share |", "|---|---|---|");
  for (const [k, n] of top) out.push(`| ${k} | ${n} | ${pct(n, bars)} |`);
  out.push("");
  // Leaps by sounding role.
  const role = { bass: [0, 0], upper: [0, 0] };
  for (const s of steps)
    for (let v = 0; v < 3; v++) {
      if (v === s.cantusIndex) continue;
      for (let k = 1; k < s.cantus.length; k++) {
        const chord = s.fux.map((l) => l[k]).map(midi);
        const r = chord.indexOf(Math.min(...chord)) === v ? role.bass : role.upper;
        r[1]++;
        if (Math.abs(midi(s.fux[v][k]) - midi(s.fux[v][k - 1])) > 2) r[0]++;
      }
    }
  out.push(`**Leaps** (moves larger than a step) of Fux's added voices: ${pct(role.bass[0], role.bass[1])} of moves landing on the sounding bass (${role.bass[1]}), ${pct(role.upper[0], role.upper[1])} of moves landing on an upper voice (${role.upper[1]}).`, "");
}
console.log("KEEP", JSON.stringify(ALL_TRIO_FEATURES.map((f, i) => [f.id, keep[i], +wKeep[i].toFixed(2)])));
writeFileSync("docs/fux/trio-habits-study.md", out.join("\n"));
console.log(out.join("\n"));
