/**
 * Writes docs/m1/m1-measurements.md: the reproducible measurements behind the M1 report.
 * Run: node tools/m1/report.ts
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { loadFuxRepository } from "../../src/music/fux/load-node.ts";
import { presetRules } from "../../src/counterpoint/engine.ts";
import { cantusReport, crossCheckAnnotations, goldenFig22PublishedReading, goldenFirstSpecies, melodicLeapAudit, widestDistances } from "./golden.ts";

const repo = loadFuxRepository();
const L: string[] = [];
const out = fileURLToPath(new URL("../../docs/m1/m1-measurements.md", import.meta.url));

L.push("# M1 measurements (generated)\n");
L.push(`Generated by \`tools/m1/report.ts\` from \`data/fux/two-voice/fux-two-voice.json\` (source commit \`${repo.dataset.provenance.commit}\`). Do not edit by hand.\n`);

L.push("## Rules in fux-strict\n");
L.push("| rule | severity | voicing | attribution | reference | pending decision |\n|---|---|---|---|---|---|");
for (const r of presetRules()) {
  L.push(`| \`${r.id}\` | ${r.severity} | ${r.voicing}${r.finals ? ` (finals ${r.finals.join(",")})` : ""} | ${r.attribution.status} | ${r.attribution.ref ?? "—"} | ${r.pending ?? ""} |`);
}
L.push("");

L.push("## Level 1 filter\n");
const l1 = repo.listExercises({ species: "first", modal_final: "C", cantus_voice: "lower" });
L.push(`Exercises with species = first, modal_final = C, cantus_voice = lower: **${l1.length}**.`);
L.push(`Exercises on final C: ${repo.listExercises({ modal_final: "C" }).map((e) => `${e.id} (${e.species}, cantus ${e.cantus_voice})`).join("; ")}.\n`);

L.push("## Golden test 1: Fux's first-species solutions under fux-strict\n");
L.push("| figure | final | cantus | errors | warnings | cantus-below rules not applied (would report) |\n|---|---|---|---|---|---|");
for (const r of goldenFirstSpecies(repo)) {
  const fmt = (vs: { ruleId: string; positions: number[]; detail?: Record<string, unknown> }[]) =>
    vs.map((v) => `\`${v.ruleId}\` @${v.positions.map((p) => p + 1).join(",")}${v.detail ? " " + JSON.stringify(v.detail) : ""}`).join("<br>") || "—";
  const na = r.not_applied_cantus_below_rules.map((x) => `\`${x.ruleId}\`: ${x.would_report.length ? fmt(x.would_report) : "ok"}`).join("<br>") || "—";
  L.push(`| ${r.figure} | ${r.modal_final} | ${r.cantus_voice} | ${fmt(r.errors)} | ${fmt(r.warnings)} | ${na} |`);
}
L.push("\nPositions are 1-based note (= bar) numbers.\n");
const f22 = goldenFig22PublishedReading(repo);
L.push(`Superseded published reading of Fig. 22 (\`${f22.counterpoint.join(" ")}\`): ${f22.evaluation.errors.map((e) => `\`${e.ruleId}\` @${e.positions.map((p) => p + 1).join(",")}`).join(", ")}.\n`);

L.push("## Golden test 2: engine intervals vs source annotations\n");
const cc = crossCheckAnnotations(repo);
L.push(`${cc.compared} annotations compared, ${cc.mismatches.length} mismatches.${cc.mismatches.length ? "\n\n" + cc.mismatches.map((m) => `- ${JSON.stringify(m)}`).join("\n") : ""}\n`);

L.push("## Golden test 3: widest distance between the voices (first species)\n");
const wd = widestDistances(repo);
L.push("| figure | cantus | widest | bar | cantus note | counterpoint note |\n|---|---|---|---|---|---|");
for (const r of wd.rows) L.push(`| ${r.figure} | ${r.cantus_voice} | ${r.interval} (${r.semitones} st) | ${r.measure} | ${r.cantus} | ${r.counterpoint} |`);
L.push(`\nMaximum: ${wd.maximum.map((r) => `${r.interval} in Fig. ${r.figure} bar ${r.measure}`).join("; ")}.\n`);

L.push("## Golden test 4: melodic intervals in all 46 Fux counterpoints vs the melodic rules\n");
const ma = melodicLeapAudit(repo);
L.push(`Consecutive sounding notes (ties merged, rests bridged); ${ma.leaps} leaps in total.\n`);
L.push("Inventory (signed): " + Object.entries(ma.inventory).sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} ×${v}`).join(", ") + "\n");
L.push("Leaps the stated rules forbid:\n");
L.push(ma.offending.length ? ma.offending.map((o) => `- ${o.exercise_id} (${o.species} species), bar ${o.measure} beat ${o.beat}: ${o.from} → ${o.to} = ${o.interval} ${o.direction} → \`${o.rule}\`${o.acrossRest ? " (across a rest)" : ""}`).join("\n") : "none");
L.push("");

L.push("## Cantus-firmus profiles (Fux's CFs used in Part I)\n");
L.push("| cf | final | figures | length | range | intervals (signed) | leaps / intervals | high point (1-based) | low point | approach to final | repeats |\n|---|---|---|---|---|---|---|---|---|---|---|");
for (const c of cantusReport(repo)) {
  const p = c.profile;
  L.push(`| \`${c.cf_id}\`${c.variant === "variant" ? " (variant)" : ""} | ${c.modal_final} | ${c.figures.join(", ")} | ${p.length} | ${p.range.lowest}–${p.range.highest} (${p.range.interval}) | ${p.intervals.join(" ")} | ${p.leaps}/${p.length - 1} | ${p.highPoint.pitch} @${p.highPoint.positions.map((x) => x + 1).join(",")} of ${p.length} | ${p.lowPoint.pitch} @${p.lowPoint.positions.map((x) => x + 1).join(",")} | ${p.finalApproach} | ${p.repeats} |`);
}
L.push("\nLeap continuations:\n");
for (const c of cantusReport(repo)) {
  L.push(`- \`${c.cf_id}\`: ${c.profile.leapContinuations.map((l) => `${l.leap} → ${l.next}${l.nextInterval ? ` (${l.nextInterval})` : ""}`).join("; ")}`);
}
L.push("");

mkdirSync(fileURLToPath(new URL("../../docs/m1/", import.meta.url)), { recursive: true });
writeFileSync(out, L.join("\n") + "\n");
console.log(`wrote ${out}`);
