// Real or tonal? Bach's 48 answers set against the rules that predict an answer from its subject.
// Written to docs/wtc/answer-study.md. Usage: node tools/wtc/answer-study.ts
import { readFileSync, writeFileSync } from "node:fs";
import { degree, names, predictAnswer, subjectAndAnswer, type AnswerRule } from "../../src/wtc/fugue.ts";
import { label, type WtcPiece } from "../../src/wtc/corpus.ts";
import { parsePitch } from "../../src/music/pitch.ts";

const fugues: WtcPiece[] = JSON.parse(readFileSync("data/wtc/fugues.json", "utf8"));
const RULES: [AnswerRule, string][] = [
  ["real", "real: the whole subject a fifth higher"],
  ["tonal-first-five", "tonal, first dominant only: the first ^5 of the head answered by ^1"],
  ["tonal-head", "tonal head: every ^5 of the head answered by ^1"],
  ["tonal-head-and-tail", "tonal head and tail: as above, and a subject ending in the dominant answered back to the tonic"],
  ["bach", "Bach's practice as a rule: a first ^5 answered by ^1; an early ^5 leapt to from ^1 answered by ^1; a tail that reaches the dominant key answered a fourth up"],
];
const pc = (p: string) => ((parsePitch(p).midi % 12) + 12) % 12;
const pct = (a: number, b: number) => `${Math.round((100 * a) / b)}%`;

interface Row {
  p: WtcPiece;
  subject: string[];
  bach: string[];
  real: string[];
  kind: string;
  departures: { i: number; deg: string; by: number }[];
}
const rows: Row[] = [];
const score = new Map<AnswerRule, { notes: number; right: number; exact: number; letters: number; lettersExact: number }>(RULES.map(([r]) => [r, { notes: 0, right: 0, exact: 0, letters: 0, lettersExact: 0 }]));
const step = (p: string) => p[0];
for (const p of fugues) {
  const { subject, answer } = subjectAndAnswer(p);
  const bach = answer.map((n) => n.pitch);
  const real = predictAnswer(subject, p.key, p.mode, "real");
  for (const [r] of RULES) {
    const pred = predictAnswer(subject, p.key, p.mode, r);
    const s = score.get(r)!;
    let ok = 0;
    let okL = 0;
    pred.forEach((x, i) => {
      ok += pc(x) === pc(bach[i]) ? 1 : 0;
      okL += step(x) === step(bach[i]) ? 1 : 0;
    });
    s.notes += pred.length;
    s.right += ok;
    s.exact += ok === pred.length ? 1 : 0;
    s.letters += okL;
    s.lettersExact += okL === pred.length ? 1 : 0;
  }
  // Where Bach departs from the real answer: the subject's degree there, and by how many semitones.
  const departures = real
    .map((x, i) => ({ i, by: ((pc(bach[i]) - pc(x) + 18) % 12) - 6 }))
    .filter((d) => d.by !== 0)
    .map((d) => {
      const g = degree(subject[d.i].pitch, p.key, p.mode);
      return { ...d, deg: `${g.alter > 0 ? "♯" : g.alter < 0 ? "♭" : ""}${g.deg}` };
    });
  const kind = !departures.length ? "real" : departures.every((d) => d.by === -2 || d.by === -1 || d.by === 1) && departures.every((d) => d.i < subject.length / 2) ? "tonal (head)" : departures.every((d) => Math.abs(d.by) <= 2) ? "tonal (head and tail)" : "other";
  rows.push({ p, subject: subject.map((n) => n.pitch), bach, real, kind, departures });
}

const kinds = new Map<string, number>();
for (const r of rows) kinds.set(r.kind, (kinds.get(r.kind) ?? 0) + 1);
const degs = new Map<string, number>();
for (const r of rows) for (const d of r.departures) degs.set(d.deg, (degs.get(d.deg) ?? 0) + 1);
const firstFive = rows.filter((r) => degree(r.subject[0], r.p.key, r.p.mode).deg === 5);
const firstFiveTonal = firstFive.filter((r) => r.departures.some((d) => d.i === 0));

// The early ^5 (notes 2-4): reached by a leap from ^1, or otherwise; is it answered by ^1?
const early = { leap: [0, 0], other: [0, 0] };
for (const r of rows) {
  const d = r.subject.map((x) => degree(x, r.p.key, r.p.mode));
  for (let i = 1; i < Math.min(4, d.length); i++) {
    if (d[i].deg !== 5 || d[i].alter !== 0) continue;
    const leapFrom1 = d[i - 1].deg === 1 && Math.abs(parsePitch(r.subject[i]).diatonic - parsePitch(r.subject[i - 1]).diatonic) >= 3;
    const mutated = r.departures.some((x) => x.i === i);
    const c = leapFrom1 ? early.leap : early.other;
    c[0]++;
    if (mutated) c[1]++;
    break;
  }
}
const out: string[] = [
  "# Real or tonal? Bach's answers in the Well-Tempered Clavier",
  "",
  "Generated by `node tools/wtc/answer-study.ts` (analysis: `src/wtc/fugue.ts`). In each of the 48",
  "fugues the subject is the first voice's opening, as long as the second voice's opening follows it",
  "in rhythm and, but for a few notes near the head, in its intervals; the answer is that opening of",
  "the second voice. (Subjects found this way can be a few notes too long or short where a",
  "countersubject keeps the subject's rhythm; the table lists each, to check by eye.)",
  "",
  "A **real** answer is the subject a fifth higher, every interval kept. Bach's answer is compared",
  "note by note (pitch class) with that, and with three tonal rules of the textbooks, applied",
  "mechanically:",
  "",
  ...RULES.map(([, d]) => `- ${d}`),
  "",
  "The *head*: the subject up to its first note on ^3, ^4 or ^6, or the end of its first bar.",
  "",
  "## How well the rules predict Bach",
  "",
  "**Letters** compares only the letter of each note (a fifth or a fourth up: the tonal question);",
  "**notes** the pitch, accidentals included (in minor, the answer's raised or natural sixth and",
  "seventh are a separate matter, which no tonal rule addresses).",
  "",
  "| rule | letters right | answers right in every letter | notes right | answers right in every note |",
  "|---|---|---|---|---|",
  ...RULES.map(([r, d]) => {
    const s = score.get(r)!;
    return `| ${d.split(":")[0]} | ${pct(s.letters, s.notes)} | ${s.lettersExact} of ${rows.length} | ${pct(s.right, s.notes)} | ${s.exact} of ${rows.length} |`;
  }),
  "",
  "## What Bach does",
  "",
  `By the departures from the real answer: ${[...kinds].map(([k, n]) => `${k} ${n}`).join(", ")}.`,
  "",
  `Departures by the subject's scale degree where they happen: ${[...degs].sort((a, b) => b[1] - a[1]).map(([d, n]) => `^${d} ${n}`).join(", ")}.`,
  "",
  `Subjects that begin on the dominant: ${firstFive.length}; Bach answers that first note with the tonic in ${firstFiveTonal.length} of them.`,
  "",
  `A ^5 among notes 2-4 (subjects not beginning on ^5): reached by a leap from ^1, ${early.leap[0]} subjects, answered by ^1 in ${early.leap[1]}; reached otherwise (by step, or from another degree), ${early.other[0]}, answered by ^1 in ${early.other[1]}.`,
  "",
  "**Reading.** The head of the answer is law-like in the 48: a subject that begins on the dominant",
  "is answered from the tonic, always, and an early dominant leapt to from the tonic is answered by",
  "the tonic, while one reached by step or from another degree mostly stays real (7 of 9; the C",
  "major fugue of Book I: C D E F G, answered G A B C D). That is the textbook rule of the tonic-dominant exchange, and Bach keeps it. The tail",
  "is not law-like: where a subject drifts to the dominant key, Bach answers some part of its end a",
  "fourth up, but where that part begins varies (from a raised fourth, from the last notes, or, in",
  "Book I no. 18 and no. 24, from the second note on), and the mechanical tail rules gain nothing",
  "over the head rule alone. In minor, the answer's sixth and seventh follow the dominant key's",
  "minor (raised in rising lines, natural in falling ones), a separate matter of accidentals. For",
  "the game: \"write the answer\" can be judged by the head rule exactly, and the tail compared with",
  "Bach's own answer, as a choice with his solution beside it.",
  "",
  "| fugue | subject (notes) | Bach's answer | departs from real at | kind |",
  "|---|---|---|---|---|",
  ...rows.map((r) => `| ${label(r.p).replace(/ \(.*/, "")} (${r.p.book === 1 ? "I" : "II"}) | ${names(r.subject).join(" ")} | ${names(r.bach).join(" ")} | ${r.departures.map((d) => `note ${d.i + 1} (^${d.deg}, ${d.by > 0 ? "+" : ""}${d.by})`).join(", ") || "–"} | ${r.kind} |`),
  "",
];
writeFileSync("docs/wtc/answer-study.md", out.join("\n"));
console.log(out.slice(15, 32).join("\n"));
