// Countersubjects in the 48: regular or free, used above and below the subject, and how Bach writes
// a line that can be inverted at the octave (the fifths and fourths between subject and
// countersubject). Written to docs/wtc/countersubject-study.md. Usage: node tools/wtc/countersubject-study.ts
import { readFileSync, writeFileSync } from "node:fs";
import { findEntries, line, subjectAndAnswer } from "../../src/wtc/fugue.ts";
import { countersubjectCandidate, countersubjectUses, verticals, within } from "../../src/wtc/countersubject.ts";
import { label, TPQ, type WtcPiece } from "../../src/wtc/corpus.ts";

const fugues: WtcPiece[] = JSON.parse(readFileSync("data/wtc/fugues.json", "utf8"));
const pct = (a: number, b: number) => (b ? `${Math.round((100 * a) / b)}%` : "–");
const rows: string[] = [];
let regular = 0;
let both = 0;
// Interval counts between subject (or answer) and countersubject, strong and weak beats, over the
// fugues with a regular countersubject; and, for comparison, between the subject and the other
// voices' free counterpoint at later entries.
const tally = (o: Record<string, number>, k: string) => (o[k] = (o[k] ?? 0) + 1);
const csStrong: Record<string, number> = {};
const csWeak: Record<string, number> = {};
const freeStrong: Record<string, number> = {};
for (const p of fugues) {
  const { subject, answer, first } = subjectAndAnswer(p);
  const entries = findEntries(p, subject);
  const cs = countersubjectCandidate(p, first, answer);
  const uses = countersubjectUses(p, cs, entries);
  const later = Math.max(0, entries.length - 1);
  const isRegular = uses.length >= 2 && uses.length >= later / 3;
  const above = uses.filter((u) => u.above).length;
  const below = uses.length - above;
  if (isRegular) {
    regular++;
    if (above && below) both++;
    // The answer against the countersubject, as first heard.
    const v = verticals(answer, cs);
    for (const x of v.pairs) tally(x.strong ? csStrong : csWeak, String(x.simple));
  } else {
    // The answer against what the first voice plays (free counterpoint): the comparison.
    const free = within(line(p.voices[first]), answer[0].on, answer[answer.length - 1].on + answer[answer.length - 1].dur);
    for (const x of verticals(answer, free).pairs) if (x.strong) tally(freeStrong, String(x.simple));
  }
  rows.push(`| ${label(p).replace(/ \(.*/, "")} (${p.book === 1 ? "I" : "II"}) | ${cs.length} | ${uses.length} of ${later} | ${isRegular ? "regular" : "free"} | ${uses.length ? `${above} above, ${below} below` : "–"} |`);
}
const share = (o: Record<string, number>) => {
  const n = Object.values(o).reduce((a, b) => a + b, 0);
  return ["1", "3", "5", "6", "4", "2", "7"].map((k) => `${k === "1" ? "8/1" : k}: ${pct(o[k] ?? 0, n)}`).join(", ") + ` (n = ${n})`;
};
const out = [
  "# Countersubjects in the 48",
  "",
  "Generated by `node tools/wtc/countersubject-study.ts` (`src/wtc/countersubject.ts`). The",
  "countersubject candidate is what the subject's voice plays while the second voice answers. It",
  "counts as **regular** when it returns, by its intervals and rhythm (at least 60% kept), against",
  "at least two later entries and a third of them; **above/below**: where it lies against those",
  "entries (both means Bach inverts it, so it must work in invertible counterpoint at the octave).",
  "The entries are found automatically (`findEntries`), so counts are approximate.",
  "",
  `Regular countersubjects: ${regular} of ${fugues.length} fugues; used both above and below the subject in ${both} of them.`,
  "",
  "**Intervals between the answer and the countersubject** (simple, by letter; at every onset of",
  "either line), in the fugues with a regular countersubject:",
  "",
  `- on the beat: ${share(csStrong)}`,
  `- off the beat: ${share(csWeak)}`,
  "",
  `For comparison, on the beat between the answer and free counterpoint (fugues without a regular countersubject): ${share(freeStrong)}.`,
  "",
  "**Reading.** Inverted at the octave, a third becomes a sixth and a sixth a third (both still",
  "consonant); an octave stays an octave; but a fifth becomes a fourth, a dissonance against the",
  "lower voice. The textbook expects a countersubject meant for inversion to avoid fifths with the",
  "subject on the beat. In these counts it does not: fifths on the beat are 11% against the",
  "countersubject and 11% against free counterpoint, and thirds and sixths dominate both (about 60%).",
  "Two readings remain open: in three and four voices the lower of the pair is often not the bass,",
  "and a fourth between upper voices is no fault (Fux says as much for three voices), so Bach need",
  "not avoid the fifth; or the test is too coarse (it samples every onset, the beat taken as the",
  "quarter note, and the countersubject is found automatically). The next test: only the inverted",
  "uses, and only where the countersubject is the lowest sounding voice.",
  "",
  "| fugue | countersubject notes | later entries with it | kind | where |",
  "|---|---|---|---|---|",
  ...rows,
  "",
];
void TPQ;
writeFileSync("docs/wtc/countersubject-study.md", out.join("\n"));
console.log(out.slice(9, 20).join("\n"));
