#!/usr/bin/env python3
"""Three automatic readings of the WTC fugue expositions, side by side.

Three sessions read the 48 the same night, by different methods:

  here   this branch: tools/wtc/fugues.py on the Humdrum encoding (data/wtc/fugue-analysis.json), answers
         classified by tools/wtc/answers.py;
  lab    the Choices-lab session (branch claude/beautiful-mccarthy-7li5nv): src/wtc/fugue.ts on
         its own parse of the same Humdrum encoding (subjectAndAnswer, predictAnswer "real");
  D119   the main session (branch claude/continuo-integration, data/bach/wtc/fugues.json): the
         ASAP scores, 29 fugues.

Compared: the subject (the same notes, or one a prefix of another: they differ only in where the
subject ends) and the mutated notes of the answer (indices where the answer's letter is not the
real answer's, within the shortest subject). Where all three agree, each confirms the others.

The lab's reading is produced by running its code on a read-only checkout of its branch:
    git worktree add --detach <dir>/lab origin/claude/beautiful-mccarthy-7li5nv
    (a 10-line script importing subjectAndAnswer and predictAnswer, writing <dir>/labdump.json)
and passed as the first argument. D119's is read through git. Output: docs/wtc/THREE-READINGS.md.

Run:  python3 tools/wtc/crosscheck.py <labdump.json>
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from answers import answers  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
REPORT = ROOT / "docs" / "wtc" / "THREE-READINGS.md"
letters = lambda ps: [p.rstrip("0123456789-") for p in ps]  # noqa: E731


def mut(real: list[str], ans: list[str], n: int) -> list[int]:
    return [i for i in range(min(n, len(real), len(ans))) if real[i][0] != ans[i][0]]


def rel(a: list[str], b: list[str]) -> str:
    la, lb = letters(a), letters(b)
    n = min(len(la), len(lb))
    if la[:n] != lb[:n]:
        return f"differ at {next(i for i in range(n) if la[i] != lb[i]) + 1}"
    return "same" if len(la) == len(lb) else "prefix"


def main() -> None:
    lab = {(x["book"], x["number"]): x for x in json.loads(Path(sys.argv[1]).read_text())}
    d119 = {(x["book"], x["number"]): x for x in json.loads(subprocess.run(
        ["git", "show", "origin/claude/continuo-integration:data/bach/wtc/fugues.json"], capture_output=True, text=True, check=True, cwd=ROOT).stdout)["fugues"]}
    here = json.loads((ROOT / "data" / "wtc" / "fugue-analysis.json").read_text())["fugues"]
    rows = []
    agree_lab = agree_d = agree_all = n_d = subj_lab = 0
    for f in here:
        k = (f["book"], f["number"])
        a = answers(f)
        h_s = f["subject"]["notes"]
        l = lab[k]
        n = min(len(h_s), len(l["subject"]))
        m_here = mut(a["real"], a["bach"], n)
        m_lab = mut(l["real"], l["answer"], n)
        ok_lab = m_here == m_lab
        agree_lab += ok_lab
        subj_lab += rel(h_s, l["subject"]) in ("same", "prefix")
        d = d119.get(k)
        cell_d = "–"
        if d:
            n_d += 1
            ds = [x["pitch"] for x in d["subject"]]
            nn = min(n, len(ds))
            m_d = [i for i in d["mutations"] if i < nn]
            mh, ml = [i for i in m_here if i < nn], [i for i in m_lab if i < nn]
            ok_d = mh == m_d
            agree_d += ok_d
            agree_all += ok_d and ml == m_d
            cell_d = f"{len(ds)} ({rel(h_s, ds)}) | {' '.join(str(i + 1) for i in m_d) or '–'} | {'agree' if ok_d else '**differ**'}"
        else:
            cell_d = "– | – | –"
        rows.append(f"| {f['book']}/{f['number']} | {f['key']} | {len(h_s)} / {len(l['subject'])} ({rel(h_s, l['subject'])}) | "
                    f"{' '.join(str(i + 1) for i in m_here) or '–'} / {' '.join(str(i + 1) for i in m_lab) or '–'} | {'agree' if ok_lab else '**differ**'} | {cell_d} |")
    md = ["# Three readings of the WTC expositions", "",
          "Generated by `tools/wtc/crosscheck.py` (method and sources in its docstring): this branch (Humdrum, `fugues.py`),",
          "the Choices lab (Humdrum, its own parser and method), and the main session's D119 (ASAP scores, 29 fugues).", "",
          f"- Subjects, here and lab: the same notes or one a prefix of the other in {subj_lab} of 48 (they differ, if at all, in where the subject ends).",
          f"- Mutated notes of the answer, here and lab: agree in {agree_lab} of 48.",
          f"- Mutated notes, here and D119: agree in {agree_d} of {n_d}; all three agree in {agree_all} of {n_d}.", "",
          "| fugue | key | subject notes, here / lab | mutated, here / lab | | D119 subject notes | D119 mutated | here vs D119 |",
          "|---|---|---|---|---|---|---|---|"] + rows
    md += ["", "Mutations are compared by letter (the lab's convention), within the shorter subject. Where the readings measure",
           "the answer from different reference transpositions (Book I no. 18: a fifth up or a fourth up), the same answer",
           "shows different mutated notes; the lab's `docs/wtc/crosscheck.md` explains that case."]
    REPORT.write_text("\n".join(md) + "\n")
    print("\n".join(md[5:8]))


if __name__ == "__main__":
    main()
