// Two independent readings of the WTC expositions set side by side: this branch's (Humdrum encoding,
// src/wtc/fugue.ts) and the main session's (ASAP scores, data/bach/wtc/fugues.json on branch
// claude/continuo-integration, D119; read through git, not copied). Where they agree on the subject
// and on which notes of the answer are mutated, each confirms the other; where not, a fugue to
// check by hand. Written to docs/wtc/crosscheck.md. Usage: node tools/wtc/crosscheck.ts
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { names, predictAnswer, subjectAndAnswer } from "../../src/wtc/fugue.ts";
import { label, type WtcPiece } from "../../src/wtc/corpus.ts";

interface Theirs {
  id: string;
  book: number;
  number: number;
  subject: { pitch: string }[];
  answer: { pitch: string }[];
  mutations: number[];
}
const theirs: Theirs[] = JSON.parse(execSync("git show origin/claude/continuo-integration:data/bach/wtc/fugues.json", { maxBuffer: 1 << 26 }).toString()).fugues;
const mine: WtcPiece[] = JSON.parse(readFileSync("data/wtc/fugues.json", "utf8"));
const pc = (ps: string[]) => names(ps);
const rows: string[] = [];
let sameSubject = 0;
let prefix = 0;
let sameMut = 0;
for (const t of theirs) {
  const p = mine.find((m) => m.book === t.book && m.number === t.number)!;
  const { subject, answer } = subjectAndAnswer(p);
  const a = pc(subject.map((n) => n.pitch));
  const b = pc(t.subject.map((n) => n.pitch));
  const n = Math.min(a.length, b.length);
  const common = a.slice(0, n).every((x, i) => x === b[i]);
  const exact = common && a.length === b.length;
  if (exact) sameSubject++;
  else if (common) prefix++;
  // Mutated notes: where the answer's letter is not the real transposition's.
  const real = predictAnswer(subject, p.key, p.mode, "real");
  const myMut = real.map((x, i) => (x[0] !== answer[i].pitch[0] ? i : -1)).filter((i) => i >= 0 && i < n);
  const theirMut = (t.mutations ?? []).filter((i) => i < n);
  const mutAgree = myMut.length === theirMut.length && myMut.every((x, i) => x === theirMut[i]);
  if (mutAgree) sameMut++;
  rows.push(`| ${label(p).replace(/ \(.*/, "")} (${p.book === 1 ? "I" : "II"}) | ${a.length} / ${b.length} | ${exact ? "same" : common ? "one is a prefix" : `differ at note ${a.findIndex((x, i) => x !== b[i]) + 1}`} | ${myMut.map((i) => i + 1).join(" ") || "–"} / ${theirMut.map((i) => i + 1).join(" ") || "–"} | ${mutAgree ? "agree" : "**differ**"} |`);
}
const out = [
  "# Two readings of the WTC expositions compared",
  "",
  "Generated by `node tools/wtc/crosscheck.ts`. This branch reads the subject and answer from the",
  "Humdrum encoding (Huron 1994; `src/wtc/fugue.ts`); the main session (D119) from the ASAP scores",
  "(`data/bach/wtc/fugues.json`, 29 fugues). Both are automatic, by different methods on different",
  "encodings: where they agree, each confirms the other.",
  "",
  `Of ${theirs.length} fugues: the same subject (every note) in ${sameSubject}; one reading's subject a prefix of the other's (they differ only in where the subject ends) in ${prefix}; the mutated notes of the answer (within the shorter subject) the same in ${sameMut}.`,
  "",
  "**Reading.** The two readings confirm each other on what matters for the answer exercise: the",
  "mutated notes agree in all but two fugues, and neither is a real disagreement. Where the subjects differ, it is only in where the",
  "subject ends, which is genuinely open where subject and countersubject run on together. The two",
  "disagreements: Book I no. 18 (G♯ minor) is not one. Bach answers its first note at the fifth (G♯",
  "by D♯) and everything after at the fourth (the subject heads for the dominant, so the answer comes",
  "home to the tonic). Measured from a fifth up, as here, notes 2-15 are \"mutated\"; measured from",
  "a fourth up, as D119 does (its answerShift 5), only note 1 is: the same answer, two reference",
  "points. Book II no. 11 (F major) is not one either: both encodings have B♭3 as the answer's second",
  "note (C B♭ C F answering F E F C). A real answer, in C, would have B natural; B♭ keeps the answer's",
  "head in F. Here mutations are counted by letter (B♭ is still a B, so only the chromatic inflection",
  "differs), D119 counts by semitone. The interval mutation, note 4 (C answered by F), is in both.",
  "",
  "| fugue | subject notes (here / D119) | subjects | mutated notes (here / D119) | mutations |",
  "|---|---|---|---|---|",
  ...rows,
  "",
];
writeFileSync("docs/wtc/crosscheck.md", out.join("\n"));
console.log(out.slice(7, 8).join("\n"));
console.log(rows.filter((r) => r.includes("differ")).join("\n"));
