// The expositions of the 48 fugues: the order the voices come in, subject and answer alternating,
// the links (codettas) between entries. Written to docs/wtc/exposition-study.md.
// Usage: node tools/wtc/exposition-study.ts
import { readFileSync, writeFileSync } from "node:fs";
import { findEntriesByHead, subjectAndAnswer } from "../../src/wtc/fugue.ts";
import { exposition, orderName, voiceNames } from "../../src/wtc/exposition.ts";
import { TPQ, label, type WtcPiece } from "../../src/wtc/corpus.ts";

const fugues: WtcPiece[] = JSON.parse(readFileSync("data/wtc/fugues.json", "utf8"));
const orders = new Map<number, Map<string, number>>();
const rows: string[] = [];
let alternating = 0;
let adjacent = 0;
let pairs = 0;
let firstMiddle = 0;
let firstCount = 0;
const links = new Map<number, [number, number]>(); // position -> [with link, total]
const roles = new Map<string, number>();
for (const p of fugues) {
  const { subject, answer } = subjectAndAnswer(p);
  const { entries } = findEntriesByHead(p, subject);
  const expo = exposition(p, subject, answer, entries);
  const n = p.voices.length;
  const name = orderName(p, expo);
  if (!orders.has(n)) orders.set(n, new Map());
  orders.get(n)!.set(name, (orders.get(n)!.get(name) ?? 0) + 1);
  const rs = expo.map((e) => e.role);
  rs.forEach((r) => roles.set(r, (roles.get(r) ?? 0) + 1));
  const alt = rs.every((r, i) => r === (i % 2 ? "answer" : "subject"));
  if (alt) alternating++;
  if (n > 2) {
    firstCount++;
    if (expo[0].voice !== 0 && expo[0].voice !== n - 1) firstMiddle++;
  }
  const [num, den] = p.meter.split("/").map(Number);
  const beat = (4 * TPQ) / den;
  expo.forEach((e, i) => {
    if (i === 0) return;
    pairs++;
    if (Math.abs(e.voice - expo[i - 1].voice) === 1) adjacent++;
    const l = links.get(i) ?? [0, 0];
    if (e.link >= beat) l[0]++;
    l[1]++;
    links.set(i, l);
  });
  const fmt = expo.map((e, i) => `${voiceNames(n)[e.voice]} ${e.roman}${i && e.link >= beat ? ` (link ${Math.round((e.link / ((num * 4 * TPQ) / den)) * 4) / 4} bar)` : ""}`).join(", ");
  rows.push(`| ${label(p).replace(/ \(.*/, "")} (${p.book === 1 ? "I" : "II"}) | ${n} | ${fmt} | ${alt ? "yes" : "no"} |`);
}
const pct = (a: number, b: number) => `${Math.round((100 * a) / b)}% (${a} of ${b})`;
const out = [
  "# The expositions of the 48 fugues",
  "",
  "Generated by `node tools/wtc/exposition-study.ts` (`src/wtc/exposition.ts`). The exposition is each",
  "voice's first entry, in the order the voices come in; an entry's key is read as in the key-plan study",
  "(subject in the tonic, answer in the dominant). A **link** (codetta) is free material of at least a",
  "beat between the end of one entry (the subject's length after it begins) and the next. Entries are",
  "found automatically; where a voice does not begin with the subject (within a bar of its first note),",
  "it is marked free.",
  "",
  "## Findings",
  "",
  `- **Subject and answer alternate** (tonic, dominant, tonic, ...) in ${pct(alternating, fugues.length)} of the expositions.`,
  `- Roles of all exposition entries: ${[...roles].sort((a, b) => b[1] - a[1]).map(([r, c]) => `${r} ${c}`).join(", ")}.`,
  `- **Adjacent voices answer each other** (each new voice next to the one before it): ${pct(adjacent, pairs)} of successive pairs.`,
  `- **The first voice is an inner voice** in ${pct(firstMiddle, firstCount)} of the fugues in three or more voices.`,
  `- **Links**: ${[...links].sort((a, b) => a[0] - b[0]).map(([i, [w, t]]) => `before entry ${i + 1}, ${pct(w, t)}`).join("; ")}.`,
  "",
  "The orders of entry, by number of voices:",
  "",
  ...[...orders].sort((a, b) => a[0] - b[0]).map(([n, m]) => `- ${n} voices: ${[...m].sort((a, b) => b[1] - a[1]).map(([o, c]) => `${o} ${c}`).join("; ")}`),
  "",
  "| fugue | voices | exposition | alternating |",
  "|---|---|---|---|",
  ...rows,
  "",
];
writeFileSync("docs/wtc/exposition-study.md", out.join("\n"));
console.log(out.slice(9, 25).join("\n"));
