#!/usr/bin/env python3
"""Import the 96 movements of the Well-Tempered Clavier into note-level JSON (LOCAL ONLY).

Input : data/local/sources/bach-wtc/kern/wtc{1,2}{p,f}NN.krn  (tools/wtc/fetch_wtc.sh)
Output: data/local/wtc/wtc{1,2}{p,f}NN.json and data/local/wtc/index.json; a validation summary
        in docs/wtc/IMPORT-LOCAL.md (counts only: committed).

Not committed (data/local/ is ignored): the encodings' rights notices reserve derivative
electronic formats. See tools/wtc/fetch_wtc.sh.

Run:  python3 tools/wtc/import_wtc.py
"""
from __future__ import annotations

import json
import re
import sys
from fractions import Fraction as F
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from kern_reader import read  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "data" / "local" / "sources" / "bach-wtc" / "kern"
OUT = ROOT / "data" / "local" / "wtc"
REPORT = ROOT / "docs" / "wtc" / "IMPORT-LOCAL.md"
fr = lambda x: f"{x.numerator}/{x.denominator}"  # noqa: E731

KEYS = {  # the key of each pair, in the order of the book
    1: "C", 2: "c", 3: "C#", 4: "c#", 5: "D", 6: "d", 7: "Eb", 8: "eb/d#", 9: "E", 10: "e", 11: "F", 12: "f",
    13: "F#", 14: "f#", 15: "G", 16: "g", 17: "Ab", 18: "g#", 19: "A", 20: "a", 21: "Bb", 22: "bb", 23: "B", 24: "b",
}


def main() -> None:
    files = sorted(SRC.glob("wtc*.krn"))
    if len(files) != 96:
        raise SystemExit(f"expected 96 files, found {len(files)} (run tools/wtc/fetch_wtc.sh)")
    OUT.mkdir(parents=True, exist_ok=True)
    index = []
    lines = ["# The Well-Tempered Clavier: import", "",
             "Generated by `tools/wtc/import_wtc.py` from the Humdrum edition (humdrum-tools/bach-wtc, pinned in",
             "`tools/wtc/fetch_wtc.sh`). The note-level data stay local (`data/local/`, not committed: the encodings'",
             "rights notices reserve derivative electronic formats); this report gives counts only.", "",
             "| movement | BWV | key | metre | bars | spines (max) | voices (spines at the start) | notes | problems |",
             "|---|---|---|---|---|---|---|---|---|"]
    total_problems = 0
    for f in files:
        m = re.match(r"wtc([12])([pf])(\d\d)\.krn", f.name)
        book, kind, no = int(m.group(1)), {"p": "prelude", "f": "fugue"}[m.group(2)], int(m.group(3))
        p = read(f)
        spines = sorted({n.spine for n in p.notes})
        sounding = [n for n in p.notes if n.pitch]
        piece = {
            "id": f.stem, "book": book, "kind": kind, "number": no, "key": KEYS[no],
            "bwv": p.refs.get("SCT"), "title": p.refs.get("OTL"), "description": p.refs.get("ONB"),
            "rights": p.refs.get("YEC"), "keys": [{"onset": fr(k["onset"]), "key": k["key"]} for k in p.keys],
            "meters": sorted({m["meter"] for m in p.meters}),
            "measures": [{"number": x["number"], "onset": fr(x["onset"]), "style": x["style"]} for x in p.measures],
            "length": fr(p.length), "spines_initial": p.spines_initial, "spines": spines,
            "notes": [{"spine": n.spine, "onset": fr(n.onset), "duration": fr(n.duration), "pitch": n.pitch, "midi": n.midi,
                       **({"tie": n.tie} if n.tie else {}), **({"fermata": True} if n.fermata else {}), **({"grace": True} if n.grace else {}),
                       "measure": n.measure} for n in p.notes],
            "problems": p.problems,
        }
        (OUT / f"{f.stem}.json").write_text(json.dumps(piece, separators=(",", ":")) + "\n")
        index.append({k: piece[k] for k in ("id", "book", "kind", "number", "key", "bwv", "description", "length", "spines_initial")} | {"notes": len(sounding)})
        total_problems += len(p.problems)
        lines.append(f"| {f.stem} | {piece['bwv']} | {KEYS[no]} | {', '.join(piece['meters'])} | {p.measures[-1]['number']} | {len(spines)} | {p.spines_initial} | {len(sounding)} | {len(p.problems)} |")
    (OUT / "index.json").write_text(json.dumps(index, indent=1) + "\n")
    lines.insert(6, f"**{len(files)} movements, {sum(x['notes'] for x in index)} notes, {total_problems} problems.**\n")
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines) + "\n")
    print(f"{len(files)} movements, {sum(x['notes'] for x in index)} notes, {total_problems} problems")


if __name__ == "__main__":
    main()
