// The Well-Tempered Clavier, imported: data/sources/bach-wtc/kern/*.krn → data/wtc/{fugues,preludes}.json,
// with a validation report (docs/wtc/IMPORT.md). Usage: node tools/wtc/import.ts
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { parseKern, TPQ } from "../../src/wtc/kern.ts";
import { pieceFromKern, type WtcPiece } from "../../src/wtc/corpus.ts";

const dir = "data/sources/bach-wtc/kern";
const fugues: WtcPiece[] = [];
const preludes: WtcPiece[] = [];
const report: string[] = [
  "# The Well-Tempered Clavier: import check",
  "",
  "Generated by `node tools/wtc/import.ts` from `data/sources/bach-wtc` (see its SOURCE.md). For each",
  "piece: voices, notes, bars; **bar check**: bars whose length (bar line to bar line) is not the",
  "meter's (the first, a pickup, and the last are allowed to differ); **voice ends**: voices whose",
  "last note ends more than a bar before the piece's end (a sign of a lost spine).",
  "",
  "| piece | key | voices | notes | bars | bar check | voice ends |",
  "|---|---|---|---|---|---|---|",
];
let problems = 0;
for (const f of readdirSync(dir).filter((x) => x.endsWith(".krn")).sort()) {
  const k = parseKern(readFileSync(`${dir}/${f}`, "utf8"));
  const p = pieceFromKern(f.replace(".krn", ""), k);
  (p.kind === "fugue" ? fugues : preludes).push(p);
  const [num, den] = (k.meter ?? "4/4").split("/").map(Number);
  const barLen = (num * 4 * TPQ) / den;
  const odd = k.bars.slice(1, -1).filter((b, i, a) => i + 1 < a.length && a[i + 1].on - b.on !== barLen && !(b.n === a[i + 1].n));
  const ends = p.voices.filter((v) => v.length && v[v.length - 1][0] + v[v.length - 1][1] < k.length - barLen).length;
  if (odd.length || ends) problems++;
  report.push(`| ${p.id} | ${p.key} | ${p.voices.length} | ${p.voices.reduce((a, v) => a + v.length, 0)} | ${k.bars.length} | ${odd.length ? `${odd.length} odd (bar ${odd.slice(0, 3).map((b) => b.n).join(", ")})` : "ok"} | ${ends ? `${ends} early` : "ok"} |`);
}
report.splice(7, 0, `${fugues.length} fugues, ${preludes.length} preludes; ${problems} pieces with something to look at.`, "");
mkdirSync("data/wtc", { recursive: true });
mkdirSync("docs/wtc", { recursive: true });
writeFileSync("data/wtc/fugues.json", JSON.stringify(fugues));
writeFileSync("data/wtc/preludes.json", JSON.stringify(preludes));
writeFileSync("docs/wtc/IMPORT.md", report.join("\n") + "\n");
console.log(report.slice(0, 10).join("\n"));
console.log(`problems: ${problems}`);
