// The key plans of the 48 fugues: the key of every entry of the subject, the exposition and the
// middle entries. Written to docs/wtc/keyplan-study.md. Usage: node tools/wtc/keyplan-study.ts
import { readFileSync, writeFileSync } from "node:fs";
import { findEntries, subjectAndAnswer } from "../../src/wtc/fugue.ts";
import { entryKey } from "../../src/wtc/keyplan.ts";
import { label, type WtcPiece } from "../../src/wtc/corpus.ts";

const fugues: WtcPiece[] = JSON.parse(readFileSync("data/wtc/fugues.json", "utf8"));
const middle = { major: new Map<string, number>(), minor: new Map<string, number>() };
const firstAway = { major: new Map<string, number>(), minor: new Map<string, number>() };
const rows: string[] = [];
for (const p of fugues) {
  const { subject } = subjectAndAnswer(p);
  const entries = findEntries(p, subject).filter((e) => e.form === "subject");
  const keys = entries.map((e) => entryKey(p, e, subject).roman);
  // The exposition: the first entries, one per voice.
  const seen = new Set<number>();
  let expo = 0;
  for (const e of entries) {
    if (seen.has(e.voice)) break;
    seen.add(e.voice);
    expo++;
  }
  const mids = keys.slice(expo);
  for (const k of mids) middle[p.mode].set(k, (middle[p.mode].get(k) ?? 0) + 1);
  const away = mids.find((k) => !["I", "i", "V", "v"].includes(k));
  if (away) firstAway[p.mode].set(away, (firstAway[p.mode].get(away) ?? 0) + 1);
  rows.push(`| ${label(p).replace(/ \(.*/, "")} (${p.book === 1 ? "I" : "II"}) | ${keys.slice(0, expo).join(" ")} | ${mids.join(" ") || "–"} |`);
}
const list = (m: Map<string, number>) => {
  const n = [...m.values()].reduce((a, b) => a + b, 0);
  return [...m].sort((a, b) => b[1] - a[1]).map(([k, c]) => `${k} ${Math.round((100 * c) / n)}%`).join(", ") + ` (${n})`;
};
const out = [
  "# The key plans of the 48 fugues",
  "",
  "Generated by `node tools/wtc/keyplan-study.ts` (`src/wtc/keyplan.ts`). Every entry of the subject",
  "found by `findEntries` (straight, not inverted) is given a key: its letter offset from the subject",
  "(the commonest over its notes, so that a tonal head does not mislead), with the third's quality as",
  "the entry spells it. Roman numerals relative to the home key (upper case major, lower case minor).",
  "The **exposition** is the run of entries until a voice enters a second time; the rest are the",
  "**middle and final entries**. Entries are found automatically: counts are approximate, and a few",
  "fugues whose subject the analysis cuts short or long show few entries.",
  "",
  "## The keys of the middle and final entries",
  "",
  `- in major fugues: ${list(middle.major)}`,
  `- in minor fugues: ${list(middle.minor)}`,
  "",
  "The first key away from tonic and dominant:",
  "",
  `- in major fugues: ${list(firstAway.major)}`,
  `- in minor fugues: ${list(firstAway.minor)}`,
  "",
  "| fugue | exposition | middle and final entries |",
  "|---|---|---|",
  ...rows,
  "",
];
writeFileSync("docs/wtc/keyplan-study.md", out.join("\n"));
console.log(out.slice(10, 20).join("\n"));
