#!/usr/bin/env python3
"""The Mutopia editions of the WTC, read (tools/wtc/lily.py) and checked against the Humdrum edition.

The Mutopia Project's LilyPond sources (data/wtc/sources/mutopia/BachJS/, vendored from
github.com/MutopiaProject/MutopiaProject at commit 2144afd6f52d56c5b6995b8b589ef1268b3139f0) are
public domain or CC BY-SA, so notes read from them may be committed and played by the game; the
Humdrum encodings may not (docs/DECISIONS.md, C7). Two editions of the same text should agree note
for note; where they do, the reader is right and the Mutopia text can stand in for the Humdrum one.

For every Mutopia piece with a Humdrum counterpart (data/local/wtc/, when present): the bars whose
attacks (onset and pitch, grace notes and tied continuations left out) are identical in the two.

Output: docs/wtc/MUTOPIA.md. Run: python3 tools/wtc/mutopia_check.py
"""
from __future__ import annotations

import json
import re
import sys
from collections import Counter
from fractions import Fraction as F
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import lily  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "data" / "wtc" / "sources" / "mutopia" / "BachJS"
LOCAL = ROOT / "data" / "local" / "wtc"
REPORT = ROOT / "docs" / "wtc" / "MUTOPIA.md"

# Mutopia file -> Humdrum id; the score to read is the first in the file
PIECES = {
    "BWV846/wtk1-prelude1/wtk1-prelude1.ly": "wtc1p01", "BWV846/wtk1-fugue1/wtk1-fugue1.ly": "wtc1f01",
    "BWV847/bwv847a/bwv847a.ly": "wtc1p02", "BWV847/fuga2/fuga2.ly": "wtc1f02",
    "BWV848/bwv848a/bwv848a.ly": "wtc1p03", "BWV848/bwv848b/bwv848b.ly": "wtc1f03",
    "BWV849/bwv849a/bwv849a.ly": "wtc1p04", "BWV849/bwv849b/bwv849b.ly": "wtc1f04",
    "BWV850/bwv850a/bwv850a-lys/bwv850a.ly": "wtc1p05", "BWV850/bwv850b/bwv850b-lys/bwv850b.ly": "wtc1f05",
    "BWV851/bwv851a/bwv851a.ly": "wtc1p06", "BWV851/bwv851_fugue06/bwv851_fugue06.ly": "wtc1f06",
    "BWV853/bwv853a/bwv853a.ly": "wtc1p08", "BWV853/bwv853b/bwv853b.ly": "wtc1f08",
    "BWV854/BWV854_Praeludium_IX_rh/BWV854_Praeludium_IX_rh.ly": "wtc1p09",
    "BWV855/bwv855a/bwv855a.ly": "wtc1p10", "BWV855/bwv855b/bwv855b.ly": "wtc1f10",
    "BWV856/BWV856_Praeludium11/BWV856_Praeludium11.ly": "wtc1p11", "BWV856/BWV856_Fugue11/BWV856_Fugue11.ly": "wtc1f11",
    "BWV857/BWV857_Praeludium12/BWV857_Praeludium12.ly": "wtc1p12", "BWV857/BWV857_Fuga12/BWV857_Fuga12.ly": "wtc1f12",
    "BWV860/BWV860_Praeludium15/BWV860_Praeludium15.ly": "wtc1p15", "BWV860/BWV860_Fuga15/BWV860_Fuga15.ly": "wtc1f15",
    "BWV861/BWV861_Praeludium16/BWV861_Praeludium16.ly": "wtc1p16", "BWV861/BWV861_Fuga16/BWV861_Fuga16.ly": "wtc1f16",
    "BWV862/bach-prelude17/bach-prelude17.ly": "wtc1p17", "BWV862/bach-fugue17/bach-fugue17.ly": "wtc1f17",
    "BWV865/BWV865_Praeludium20/BWV865_Praeludium20.ly": "wtc1p20", "BWV865/BWV865_Fuga20/BWV865_Fuga20.ly": "wtc1f20",
    "BWV869/BWV869_Praeludium24/BWV869_Praeludium24.ly": "wtc1p24", "BWV869/bwv869b/bwv869b-lys/bwv869b.ly": "wtc1f24",
    "BWV870/wtk2prelude1/wtk2prelude1.ly": "wtc2p01", "BWV870/wtk2fuga1/wtk2fuga1.ly": "wtc2f01",
    "BWV871/wtk2-prelude2/wtk2-prelude2.ly": "wtc2p02", "BWV871/wtk2-fugue2/wtk2-fugue2.ly": "wtc2f02",
    "BWV875/bwv875a/bwv875a.ly": "wtc2p06", "BWV878/f9/f9.ly": "wtc2f09",
}


def licence(path: Path) -> str:
    text = path.read_text(errors="replace")
    m = re.search(r'license\s*=\s*"([^"]+)"', text) or re.search(r'copyright\s*=\s*"([^"]+)"', text)
    return m.group(1) if m else "?"


def attacks_humdrum(pid: str) -> list[tuple[int, F, int]]:
    d = json.loads((LOCAL / f"{pid}.json").read_text())
    return [(n["measure"], F(n["onset"]), n["midi"]) for n in d["notes"]
            if n.get("midi") is not None and not n.get("grace") and n.get("tie") not in ("continue", "stop")]


def main() -> None:
    rows = []
    for rel, pid in PIECES.items():
        path = SRC / rel
        lic = licence(path)
        try:
            sc = lily.read(path)
        except Exception as e:  # noqa: BLE001
            rows.append((pid, rel, lic, f"not read: {e}", None, None))
            continue
        L = [(n["measure"], n["onset"], n["midi"]) for n in sc.notes if not n["grace"]]
        if not (LOCAL / f"{pid}.json").exists():
            rows.append((pid, rel, lic, f"{len(L)} notes", None, None))
            continue
        H = attacks_humdrum(pid)
        bars = sorted({m for m, _, _ in L} | {m for m, _, _ in H})
        same = sum(Counter((o, m2) for m, o, m2 in L if m == b) == Counter((o, m2) for m, o, m2 in H if m == b) for b in bars)
        rows.append((pid, rel, lic, f"{len(L)} / {len(H)}", same, len(bars)))
    md = ["# The Mutopia editions of the WTC, checked against the Humdrum edition", "",
          "Generated by `tools/wtc/mutopia_check.py` (method in its docstring), reading the LilyPond sources with",
          "`tools/wtc/lily.py`. **Identical bars**: every attack (onset and pitch) the same in both editions.", "",
          "| piece | Mutopia file | licence | attacks (Mutopia / Humdrum) | identical bars |", "|---|---|---|---|---|"]
    for pid, rel, lic, att, same, n in rows:
        md.append(f"| {pid} | `{rel}` | {lic} | {att} | {f'{same}/{n} ({100 * same / n:.0f}%)' if n else '–'} |")
    md += ["", "## The differences examined (the preludes used by the game)", "",
           "- **1/2 in C minor** (35 of 38): bar 18, the left hand's Bb2 against Humdrum's C3 (the Mutopia editor followed",
           "  the Urtext, as his comment says); bar 30, A3 against Ab3; bar 34 (Adagio), Ab4 twice against A4. Readings and",
           "  accidentals of the two editions, not of the reader.",
           "- **1/5 in D** (34 of 35): bar 33, the top D5 of the arpeggiated chord written in two voices (one notehead, two",
           "  voices); the reader keeps both, as LilyPond's own MIDI output plays it.",
           "- **1/6 in D minor** (25 of 26): bar 21, C#4 against Humdrum's C4: an accidental reading.",
           "- Lower agreements elsewhere, as far as examined: appoggiaturas written out in Humdrum and as grace notes in",
           "  Mutopia (1/4), tie marks (1/20, 2/1), repeats unfolded in LilyPond and not in Humdrum (1/24, 2/2), an ensemble",
           "  arrangement as the file's first score (2/9). The reader is not at fault in these; the editions are written",
           "  differently. Each piece is to be checked before the game uses it.", "",
           "Licences: public domain, or Creative Commons BY-SA (attribution and share-alike apply to what is derived from",
           "those files). The typesetters are named in each file's header."]
    REPORT.write_text("\n".join(md) + "\n")
    print("\n".join(md[6:6 + len(rows)]))


if __name__ == "__main__":
    main()
