#!/usr/bin/env python3
"""Which preludes are figuration preludes? (docs/wtc/PLAN.md, section 2)

A figuration prelude, like Prelude 1 in C, applies one pattern to a chord per bar (or half bar). The
test: cut the prelude into units (the bar, and the half bar), and describe each unit by its pattern,
the sequence of (onset in the unit, duration, rank of the pitch among the unit's distinct pitches),
which keeps the rhythm and the shape of the breaking and drops the chord. A prelude is as much a
figuration prelude as its units share one pattern: the share of units with the commonest pattern.
Two looser measures beside it: the same rhythm only (onsets and durations), and the same shape in
the upper part only (the bass may move freely, as in Prelude 2 in C minor's left hand).

Output: docs/wtc/PRELUDES.md (counts only). Run: python3 tools/wtc/preludes.py
"""
from __future__ import annotations

import json
from collections import Counter
from fractions import Fraction as F
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LOCAL = ROOT / "data" / "local" / "wtc"
REPORT = ROOT / "docs" / "wtc" / "PRELUDES.md"


def units(piece: dict, part: F) -> list[list[dict]]:
    """The notes of each unit (a bar, or a fraction of it), the last bar's cadence left out."""
    bars = [(F(m["onset"]), m["number"]) for m in piece["measures"] if m["number"] > 0]
    starts = sorted({t for t, _ in bars})
    length = F(piece["length"])
    ends = starts[1:] + [length]
    # the bar length is the commonest distance between bar lines
    bar = Counter(e - s for s, e in zip(starts, ends)).most_common(1)[0][0]
    step = bar * part
    notes = [n for n in piece["notes"] if n["pitch"] and not n.get("grace")]
    out = []
    t = starts[0]
    while t + step <= length - bar:  # the final bar is a cadence, not the figuration
        out.append([n for n in notes if t <= F(n["onset"]) < t + step])
        out[-1] = [dict(n, rel=F(n["onset"]) - t) for n in out[-1]]
        t += step
    return [u for u in out if u]


def pattern(unit: list[dict], what: str) -> tuple:
    pitches = sorted({n["midi"] for n in unit})
    rank = {m: i for i, m in enumerate(pitches)}
    if what == "contour":
        # per voice (spine): onset, duration, and the direction from the voice's previous note
        out = []
        by = {}
        for n in sorted(unit, key=lambda n: (n["spine"], n["rel"])):
            prev = by.get(n["spine"])
            d = 0 if prev is None else (n["midi"] > prev) - (n["midi"] < prev)
            by[n["spine"]] = n["midi"]
            out.append((n["spine"].split(".")[0], n["rel"], F(n["duration"]), d if prev is not None else "s"))
        return tuple(sorted(out, key=str))
    if what == "rhythm":
        return tuple(sorted((n["rel"], F(n["duration"])) for n in unit))
    if what == "upper":
        low = pitches[0]
        unit = [n for n in unit if n["midi"] != low]
        pitches = sorted({n["midi"] for n in unit})
        rank = {m: i for i, m in enumerate(pitches)}
    return tuple(sorted((n["rel"], F(n["duration"]), rank[n["midi"]]) for n in unit))


def share(us: list[list[dict]], what: str, near: float = 1.0) -> float:
    """Share of units whose pattern is the commonest one, or (near < 1) agrees with it in at least
    that share of its notes (the same number of notes, position by position)."""
    pats = [pattern(u, what) for u in us]
    if not pats:
        return 0.0
    mode = Counter(pats).most_common(1)[0][0]
    ok = sum(1 for x in pats if len(x) == len(mode) and sum(a == b for a, b in zip(x, mode)) >= near * len(mode))
    return ok / len(pats)


def main() -> None:
    idx = json.loads((LOCAL / "index.json").read_text())
    rows = []
    for x in idx:
        if x["kind"] != "prelude":
            continue
        piece = json.loads((LOCAL / f"{x['id']}.json").read_text())
        best = None
        for part, name in ((F(1), "bar"), (F(1, 2), "half bar")):
            us = units(piece, part)
            if len(us) < 4:
                continue
            r = {"unit": name, "n": len(us), "full": share(us, "full"), "contour": share(us, "contour", 0.8), "upper": share(us, "upper"), "rhythm": share(us, "rhythm")}
            if best is None or r["contour"] > best["contour"] + 0.05:
                best = r
        rows.append((x, best))
    rows.sort(key=lambda r: -r[1]["contour"])
    md = ["# Figuration preludes: how regularly each prelude repeats one pattern", "",
          "Generated by `tools/wtc/preludes.py` (method in its docstring) from the local Humdrum notes; counts only.",
          "Share of units (bars or half bars, the final bar left out) with the commonest pattern: **contour** (each voice's",
          "rhythm and direction of motion, note by note, agreeing with the commonest in at least 80% of its notes: the",
          "primary measure, since a chord's spacing may turn one step of the breaking), **full** (rhythm and the",
          "shape of the breaking, pitch ranks within the unit), **upper** (the same without the lowest note), **rhythm**",
          "(onsets and durations only). Prelude 1 in C, the model, should come first.", "",
          "| prelude | key | unit | units | contour | full | upper | rhythm |", "|---|---|---|---|---|---|---|---|"]
    for x, r in rows:
        md.append(f"| {x['book']}/{x['number']} | {x['key']} | {r['unit']} | {r['n']} | {100 * r['contour']:.0f}% | {100 * r['full']:.0f}% | {100 * r['upper']:.0f}% | {100 * r['rhythm']:.0f}% |")
    strong = [f"{x['book']}/{x['number']}" for x, r in rows if r["contour"] >= 0.5]
    md += ["", f"Figuration preludes by this test (one contour pattern in at least half the units): {', '.join(strong) or 'none'}.",
           "Candidates for the P1 level after Prelude 1: these, in this order."]
    REPORT.write_text("\n".join(md) + "\n")
    print("\n".join(md[9:24]))
    print(md[-2])


if __name__ == "__main__":
    main()
