#!/usr/bin/env python3
"""The Choices lab's harmonic reduction of the WTC, measured against the same human analyses as this
branch's harmonic reader (When in Rome; docs/wtc/HARMONY.md, HARMONIC-MAPS.md).

The lab's `reduce` (branch claude/beautiful-mccarthy-7li5nv, src/wtc/reduction.ts) collapses each bar
(or half bar) to the chord its notes sound, with a Roman numeral against the home key, and says of
itself that "it knows nothing of passing notes: in running preludes it is a crude reading". How
crude is measured here: at the start of every When in Rome segment, is the root of the lab's chord
there the analyst's root? Its Roman numerals are read with music21 against the piece's home key.
The same question for this branch's map (tools/wtc/harmonic_map.py) is answered beside it.

The lab's output is produced by running its code on a read-only checkout of its branch (a dozen-line
script calling reduce() for every movement, by the bar and by the half bar, writing JSON) and passed
as the first argument. Output: docs/wtc/REDUCTION-CHECK.md.

Run:  python3 tools/wtc/reduction_check.py <labred.json>
"""
from __future__ import annotations

import json
import re
import sys
import warnings
from fractions import Fraction as F
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import harmony as H  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
LOCAL = ROOT / "data" / "local" / "wtc"
MAPS = ROOT / "data" / "wtc" / "harmonic-maps.json"
REPORT = ROOT / "docs" / "wtc" / "REDUCTION-CHECK.md"


def root_pc(numeral: str, tonic: str, mode: str) -> int | None:
    from music21 import key, roman
    fig = re.sub(r"/", "", numeral)
    if not fig or "?" in fig:
        return None
    try:
        return roman.RomanNumeral(fig, key.Key(tonic if mode == "major" else tonic.lower())).root().pitchClass
    except Exception:  # noqa: BLE001
        return None


def main() -> None:
    warnings.filterwarnings("ignore")
    red = json.loads(Path(sys.argv[1]).read_text())
    maps = {p["id"]: p for p in json.loads(MAPS.read_text())["pieces"]}
    rows = []
    tot = {"bar": [0, 0, 0], "half": [0, 0, 0], "map": [0, 0]}
    for pid, path in H.wir_pieces():
        piece = json.loads((LOCAL / f"{pid}.json").read_text())
        spans = H.wir_spans(path, piece)
        cells = []
        for name in ("bar", "half"):
            r = red[f"{pid}:{name}"]
            whole = 4 * r["tpq"]
            segs = [(F(s["on"], whole), F(s["on"] + s["dur"], whole), root_pc(s["roman"], r["key"], r["mode"])) for s in r["segs"]]
            ok = n = unread = 0
            for sp in spans:
                t = sp["t"] + F(1, 1000)
                seg = next((s for s in segs if s[0] <= t < s[1]), None)
                if seg is None:
                    continue
                n += 1
                if seg[2] is None:
                    unread += 1
                ok += seg[2] == sp["root_pc"]
            tot[name][0] += ok
            tot[name][1] += n
            tot[name][2] += unread
            cells.append(f"{100 * ok / n:.0f}%" if n else "–")
        hm = maps[pid]["harmonies"]
        hs = []
        for h in hm:
            hs.append((F(h["onset"]), F(h["onset"]) + F(h["length"]), h["root"]))
        ok = n = 0
        for sp in spans:
            t = sp["t"] + F(1, 1000)
            h = next((x for x in hs if x[0] <= t < x[1]), None)
            if h is None:
                continue
            n += 1
            ok += H.spell(h[2] + "4")[1] == sp["root_pc"]
        tot["map"][0] += ok
        tot["map"][1] += n
        rows.append(f"| {pid} | {len(spans)} | {cells[0]} | {cells[1]} | {100 * ok / n:.0f}% |" if n else f"| {pid} | {len(spans)} | {cells[0]} | {cells[1]} | – |")
    pct = lambda a: f"{100 * a[0] / a[1]:.1f}%"  # noqa: E731
    md = ["# The lab's harmonic reduction, measured against human analyses", "",
          "Generated by `tools/wtc/reduction_check.py` (method in its docstring). At the start of every segment of the When in Rome",
          "analyses (31 movements): does the reading there have the analyst's root?", "",
          "| reading | root agrees |", "|---|---|",
          f"| the lab's reduction, a chord a bar | {pct(tot['bar'])}; where it gives a numeral ({tot['bar'][1] - tot['bar'][2]} of {tot['bar'][1]} segments): {pct([tot['bar'][0], tot['bar'][1] - tot['bar'][2]])} |",
          f"| the lab's reduction, a chord a half bar | {pct(tot['half'])}; where it gives a numeral ({tot['half'][1] - tot['half'][2]} of {tot['half'][1]}): {pct([tot['half'][0], tot['half'][1] - tot['half'][2]])} |",
          f"| this branch's harmonic map (half beats, passing notes discounted) | {pct(tot['map'])} |",
          "| this branch's reader given the analyst's segmentation (docs/wtc/HARMONY.md) | 83.3% |", "",
          "The lab's reduction gives no numeral (\"?\") where the notes of the bar do not stack in thirds, which in running",
          "textures is most bars: its own docstring warns of this. Where it does give one, the comparison is fair.", "",
          "The two answer different questions: a chord a bar is the progression a figuration prelude decorates (Prelude 1 in",
          "C, where the analyst too writes a chord a bar), and is meant as such; the map follows the harmony as fast as it",
          "changes. Where the analysis changes faster than the bar, a chord a bar cannot agree; the table by movement shows",
          "where each kind of reading serves. Together they suggest a division: the lab's chord-a-bar reading where it gives a",
          "numeral (rarely, but then nearly always the analyst's root), the map elsewhere.", "",
          "| movement | segments | lab, bar | lab, half bar | map |", "|---|---|---|---|---|"] + rows
    REPORT.write_text("\n".join(md) + "\n")
    print("\n".join(md[4:10]))


if __name__ == "__main__":
    main()
