// Strettos and episodes in the 48 fugues. Written to docs/wtc/structure-study.md.
// Usage: node tools/wtc/structure-study.ts
import { readFileSync, writeFileSync } from "node:fs";
import { findEntries, subjectAndAnswer } from "../../src/wtc/fugue.ts";
import { episodes, strettos } from "../../src/wtc/structure.ts";
import { label, TPQ, type WtcPiece } from "../../src/wtc/corpus.ts";

const fugues: WtcPiece[] = JSON.parse(readFileSync("data/wtc/fugues.json", "utf8"));
const pct = (a: number, b: number) => (b ? `${Math.round((100 * a) / b)}%` : "–");
const rows: string[] = [];
let withStretto = 0;
let eps = 0;
let seqs = 0;
let derived = 0;
let epTime = 0;
let total = 0;
for (const p of fugues) {
  const { subject } = subjectAndAnswer(p);
  const entries = findEntries(p, subject);
  const st = strettos(p, entries);
  const ep = episodes(p, entries, subject);
  if (st.length) withStretto++;
  eps += ep.length;
  seqs += ep.filter((e) => e.sequence).length;
  derived += ep.filter((e) => e.fromSubject).length;
  const t = ep.reduce((a, e) => a + e.end - e.on, 0);
  epTime += t;
  total += p.length;
  rows.push(`| ${label(p).replace(/ \(.*/, "")} (${p.book === 1 ? "I" : "II"}) | ${entries.length} | ${st.length} | ${ep.length} | ${pct(t, p.length)} | ${ep.filter((e) => e.sequence).length} | ${ep.filter((e) => e.fromSubject).length} |`);
}
const out = [
  "# Strettos and episodes in the 48 fugues",
  "",
  "Generated by `node tools/wtc/structure-study.ts` (`src/wtc/structure.ts`), from the entries found",
  "automatically (`findEntries`). A **stretto**: an entry beginning more than a beat before the one",
  "before it (in another voice) has ended. An **episode**: half a bar or more, after the first",
  "entry, where no entry sounds. **Sequence**: within an episode, a figure of 3-8 notes repeated at",
  "least three times, each time moved by the same step (same intervals and rhythm). **From the",
  "subject**: the sequence's figure contains a run of three of the subject's intervals.",
  "",
  `Fugues with a stretto: ${withStretto} of ${fugues.length}. Episodes: ${eps}, ${pct(epTime, total)} of the fugues' time; ${pct(seqs, eps)} of them built on a sequence, ${pct(derived, eps)} on a figure from the subject.`,
  "",
  "**Reading.** Where the entries are found reliably, the counts are a fair first map: strettos are",
  "common (most fugues overlap their entries somewhere), and episodes take a large share of the time.",
  "The sequence test is strict (exact repetition of intervals and rhythm three times): Bach often",
  "varies the figure, or repeats it only twice, so the share of sequential episodes is a lower bound;",
  "likewise 'from the subject', which asks for three of the subject's intervals in a row. Where",
  "the subject is read too long or too short (see crosscheck.md), entries are missed and episodes",
  "come out too long.",
  "",
  "| fugue | entries | strettos | episodes | episode time | sequential | from the subject |",
  "|---|---|---|---|---|---|---|",
  ...rows,
  "",
];
void TPQ;
writeFileSync("docs/wtc/structure-study.md", out.join("\n"));
console.log(out.slice(9, 10).join("\n"));
