/**
 * Schema of data/fux/two-voice/fux-two-voice.json (schema_version 1.0.0).
 *
 * Generated by tools/fux_import/build_dataset.py from the Four Score and More / Open Music Theory
 * Fux dataset (github.com/MarkGotham/species). The game never parses MusicXML at runtime.
 *
 * Conventions
 * - Pitches: scientific pitch notation, spelled exactly as in the source ("Bb3", "C#5", C4 = MIDI 60).
 * - Durations/offsets: "n/d" fractions of a whole note. In this corpus one 2/2 bar = "1/1".
 * - Staff: "upper" | "lower" staff of the two-voice score (upstream part 1 / part 2).
 */

/** "n/d" fraction of a whole note, e.g. "1/2" = half note. */
export type Rational = string;

export type Species = "first" | "second" | "third" | "fourth" | "fifth";
export type ModalFinal = "D" | "E" | "F" | "G" | "A" | "C";
export type Staff = "upper" | "lower";
export type TieState = "start" | "continue" | "stop" | null;

/** Raw MusicXML information kept from the per-exercise .mxl when it agrees with the canonical reading. */
export interface MusicXmlNoteInfo {
  file: string;
  measure: string;
  divisions: number;
  duration: number;
  type: string | null;
  dots: number;
  accidental: { value: string; editorial?: boolean; cautionary?: boolean; parentheses?: boolean; bracket?: boolean } | null;
  tie: string[] | null;
  tied: string[] | null;
}

/** An upstream editorial emendation of the 1725 print, attached to the affected note. */
export interface EditorialEmendation {
  kind: string;
  printed_1725: string;
  encoded: string;
  reason: string;
  by: string;
}

export interface Note {
  /** Index within its voice. */
  i: number;
  /** Spelled pitch, null for rests. */
  pitch: string | null;
  midi: number | null;
  rest: boolean;
  duration: Rational;
  /** Onset from the start of the exercise. */
  offset: Rational;
  /** 1-based measure number. */
  measure: number;
  /** Onset within the measure. */
  beat: Rational;
  step?: "C" | "D" | "E" | "F" | "G" | "A" | "B";
  alter?: number;
  octave?: number;
  tie: TieState;
  /** Whether the source displays an accidental sign on this note. */
  accidental_shown: boolean;
  fermata: boolean;
  grace: boolean;
  /** Original **kern token (canonical reading). */
  kern?: string;
  musicxml?: MusicXmlNoteInfo;
  editorial?: EditorialEmendation;
}

export interface Clef {
  sign: string;
  line: number;
  octave_change?: number;
  name: string;
  /** Original 1725 clef code, e.g. "C3" (only on `original`). */
  code?: string;
}

export interface ClefPair {
  /** Clef printed in the 1725 edition (from upstream metadata). */
  original: Clef;
  /** Modern clef used by the upstream MusicXML. */
  modern: Clef;
}

export interface CantusFirmusNote {
  i: number;
  pitch: string;
  midi: number;
  duration: Rational;
  step: string;
  alter: number;
  octave: number;
}

export interface CantusFirmus {
  cf_id: string;
  /** Octave-equivalence family: the same melody in other registers shares a family_id. */
  family_id: string | null;
  modal_final: ModalFinal;
  pitch_sequence: string[];
  midi_sequence: number[];
  duration_sequence: Rational[];
  length_in_notes: number;
  range: { lowest: string; highest: string; lowest_midi: number; highest_midi: number; semitones: number };
  original_register: { first: string; final: string; final_octave: number; original_clefs: string[]; note?: string };
  notes: CantusFirmusNote[];
  source_exercises: string[];
  source_figures: string[];
  cantus_voices: Staff[];
  distinct_file_entries: { index: number; label: string; cantus_voice: Staff }[];
  /** false = register found only in I-Distinct.mxl, not used by any Part I exercise. */
  in_exercises: boolean;
}

export interface FileSpan {
  file: string;
  measure_index_start: number;
  measure_count: number;
}

export interface ExerciseSource {
  upstream_id: string;
  part: "I";
  figure: string;
  figure_number: number;
  figure_suffix: string | null;
  figure_note: string | null;
  figure_corrected: boolean;
  figure_corrects: number | null;
  figure_numbering: string;
  label: string;
  species: number[];
  modal_final: string;
  cantus_firmus: { part: number; raw: "Upper" | "Lower" };
  voices: number;
  meter: string;
  measures: number;
  clefs_original: string[];
  page_1725: number | null;
  pdf: Record<string, unknown>;
  editorial: Record<string, unknown> | null;
  kern_references: Record<string, string>;
  repository: string;
  commit: string;
  files: {
    metadata: string;
    kern: string;
    musicxml: string;
    musicxml_member: string | null;
    exercises_combined: FileSpan;
    solutions_combined: FileSpan;
    annotations_combined: FileSpan;
  };
  urls: Record<string, string>;
  vendored_root: string;
}

export interface Exercise {
  id: string;
  ordinal: number;
  figure: string;
  species: Species;
  species_number: number;
  modal_final: ModalFinal;
  cantus_voice: Staff;
  counterpoint_voice: Staff;
  meter: "2/2";
  measures: number;
  difficulty: { value: number; basis: string };
  cantus_firmus: { cf_id: string; staff: Staff; staff_index: number; clef: ClefPair; notes: Note[] };
  counterpoint: {
    role: "player";
    staff: Staff;
    staff_index: number;
    clef: ClefPair;
    /** Always empty: the player's voice. */
    notes: [];
    /** How I-Exercises.mxl writes the empty staff (rests). */
    blank_source: { measure: number; rest_duration: Rational; musicxml: { duration: number | null; divisions: number; type: string | null } }[];
    /** True when those rests reproduce the rhythm of Fux's solution (do not display them if that would give it away). */
    blank_source_mirrors_solution_rhythm: boolean;
  };
  solution_id: string;
  annotation_id: string;
  source: ExerciseSource;
}

export interface ReadingDivergence {
  voice: "cantus_firmus" | "counterpoint";
  staff: Staff;
  a: string;
  b: string;
  differences: { offset: Rational; measure: number; a: string | null; b: string | null }[];
}

export interface OriginalSolution {
  id: string;
  exercise_id: string;
  role: "original_solution";
  author: "Johann Joseph Fux";
  cf_id: string;
  species: Species;
  species_number: number;
  modal_final: ModalFinal;
  cantus_voice: Staff;
  counterpoint_voice: Staff;
  clefs: { cantus: ClefPair; counterpoint: ClefPair };
  cantus_firmus: { staff: Staff; pitch_sequence: string[]; notes: Note[] };
  counterpoint: { staff: Staff; pitch_sequence: string[]; duration_sequence: Rational[]; notes: Note[] };
  source: {
    canonical_reading: "kern_vor" | "musicxml_published";
    files: ExerciseSource["files"];
    urls: Record<string, string>;
    commit: string;
    editorial: Record<string, unknown> | null;
    divergences: ReadingDivergence[];
    alternative_readings: Record<string, Record<string, string[]>>;
  };
}

export interface AnnotationItem {
  offset: Rational;
  measure: number;
  beat: Rational;
  annotated_voice: "counterpoint" | "cantus_firmus";
  /** Pitches as they stand in I-Annotations.mxl. */
  counterpoint_note: string | null;
  cantus_note: string | null;
  /** Interval text exactly as annotated in the source (e.g. "P5", "m10"). */
  interval: string;
  /** Independently computed from the two annotated pitches (verification only). */
  interval_computed: string | null;
  counterpoint_position: "above" | "below" | "unison" | null;
  agrees: boolean | null;
  /** Indices into the canonical solution voices for the notes sounding at this onset. */
  counterpoint_note_index: number | null;
  cantus_note_index: number | null;
  /** Present only where the annotated file's notes differ from the canonical reading. */
  canonical_counterpoint_note?: string | null;
  canonical_cantus_note?: string | null;
  canonical_interval_computed?: string;
}

export interface AnnotationSet {
  id: string;
  exercise_id: string;
  cf_id: string;
  source: { file: string; measure_index_start: number; measure_count: number; encoding: string };
  items: AnnotationItem[];
  unannotated_counterpoint_onsets: Rational[];
}

export interface DistinctFileEntry {
  index: number;
  label: string;
  modal_final: ModalFinal;
  cantus_voice: Staff;
  pitch_sequence: string[];
  duration_sequence: Rational[];
  file: string;
  measure_index_start: number;
  measure_count: number;
  matched_cf_id: string | null;
  match: string;
  distinct_cf_id?: string;
}

export interface SourceDiscrepancy {
  kind: string;
  exercise_id?: string;
  file?: string;
  detail?: string;
  [key: string]: unknown;
}

export interface FuxDataset {
  schema_version: string;
  dataset_id: string;
  title: string;
  generated_by: string;
  conventions: Record<string, string>;
  provenance: Record<string, unknown> & { repository: string; commit: string };
  license: Record<string, unknown>;
  counts: Record<string, unknown>;
  cantus_firmi: CantusFirmus[];
  exercises: Exercise[];
  solutions: OriginalSolution[];
  annotations: AnnotationSet[];
  distinct_file_entries: DistinctFileEntry[];
  source_discrepancies: SourceDiscrepancy[];
}
